$axure.loadCurrentPage({
  "url":"购物车.html",
  "generationDate":new Date(1458745316161.03),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"52cc505337bc4462a7d922f272a553ad",
    "type":"Axure:Page",
    "name":"购物车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e8a7ce66360415aba8293f06e9e28aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":38,
              "y":144},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4884e921d7a447418100483377d1f2a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":38,
                  "y":144},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56ae56c297ed430f8d731161f42d702c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":173},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}},
{
          "id":"05e2a04f7c34497780123fc0e96ebcfa",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":193},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b66942409aa4ac1ac69995b34d0ff01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":193},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"af9efc13813c4ae5b2ab0cc70f576795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":193},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad4642150dd42c39c5257f1d70de1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":193},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c3e8f587c2e4002917971234f4b0005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":193},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2de4d4bb1f49f6bde6f103d1652c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":193},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1978bd9c22aa450cbb23c006a29cf6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":193},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c75e8ec45e4a398d6fddae777c4b8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":193},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdad416234994b4d89ee5f96fdc31293",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":193},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"449ca9c8ad034dd0a4350d42990a4d64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":193},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97a0169862d646b3b4442d97241a858d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":193},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adcbe8ff43ab48329a6cccdcd27a1f68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":193},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05c9bee976f04cdfb3a0668d55bb496c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":219},
            "size":{
              "width":1000,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7168ec6030814b7f9d0cee8d194cd8bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":219},
                "size":{
                  "width":1000,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u15.png"}},
{
          "id":"3e81c29eca2942fdad97c461e4dac8f4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":230},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6534e83fe064e74b559a88ad71d046c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":230},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f9da0ab4e3f048cba861abd4d080e759",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":230},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25d57b3f4ed408680318dc9652542d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":230},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u19.png"}},
{
          "id":"d377deebcf7b42ceaaba0dc2b8b02dfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":272},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c274b66f65d444dbef8e440d7568810",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":272},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66018b5a00d944ffba5447a9629bc270",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":269},
            "size":{
              "width":37,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"1"},
{
          "id":"d9116d84e678495c83a54fe6b89df73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":269},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39451f9d18904a8788b00049e49efdbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":269},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4839108acea64c6ea7f2a5db3aeb4666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":260},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a2ca3be492d4c86927d62193ebbbda4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":260},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3371b55e05f47a58e8ebc43fa2d99e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":289},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b77569fd5748eba41aaf8473150f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":289},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"714b9e93954241b0bd3ada657cd7b896",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":350},
            "size":{
              "width":1000,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f6f040c38cf45a2859a6792f0f4793e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":350},
                "size":{
                  "width":1000,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u15.png"}},
{
          "id":"d6813c7f6ce04e79aa3a2207aa2aab0a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":361},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243b6ce3a6224582852735a268c13317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":361},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3df525e50ea0428aa00c13b29c89a4f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":361},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c99862b3b3044a1b69bec684c6139ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":361},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u19.png"}},
{
          "id":"fa04efd16828469c886377ee62cbfc51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":403},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff08a6b72fb48e5977686937c8d41da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":403},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"999abe1cf54f45218f9b88bf8d4e22ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":400},
            "size":{
              "width":37,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"1"},
{
          "id":"5a11bd789103494db24e7a84aa5364d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":400},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f9655d88b734aa1897d1ab6832945f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":400},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be722036da2d44428f2d150b00808da2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":391},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5689494df293456694f2dd81e820d379",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":391},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb2b83e13a14b9885794353e95e060b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":420},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ce2678a8c6642a2a70d4286f4cf7372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":420},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bee2bd166344c368583704d2677bb97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":489},
            "size":{
              "width":1000,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2dd840484ba47adb07821cb9afcf666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":489},
                "size":{
                  "width":1000,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u15.png"}},
{
          "id":"30ca4a753f6542d0a6db287856374732",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":500},
            "size":{
              "width":12,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f4cbe3d00b47949b92512eaaf2c7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":500},
                "size":{
                  "width":12,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"96e459f55e344755addb34053a794e9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":500},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3a78626bcf4ad799086ae4ec7f9fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":500},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u19.png"}},
{
          "id":"4c9cfda627b74ec49ab9765d6674129e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":542},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcf123cb6cff46839115c01422628d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":542},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abecabf4216b4cbe8f719f451d5bcf86",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":539},
            "size":{
              "width":37,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"1"},
{
          "id":"accb6ed3feba44d2a26798abf5b57284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":539},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783dd588d2384805ae769e80b8218729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":539},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bc23b3331b74f1296fcff0d0a35c3e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":530},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a339450bb03d4f4fbdb05779ea82ac13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":530},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"153db4dc64ec4aebb094a338d81c3837",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":559},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d0cb1922b64b0dbec5f422d1a1e19a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":559},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fabe44397c3488990be9006b1d21583",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":630},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fd0a40c2bb245f7a81f1130c86cd6b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":630},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9526e4b8a6db45d7ac3198f3cf5ece1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":630},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5979a36a019f44e691afc4ff76730463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":630},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76f9a6aea4a348afa36e94ae1b381809",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":628},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"095d467f4334439eabab460c05ad4c67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":628},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eefa88add3cc4bd2bc3921a7f4520957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":628},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f90dc65a1b482d8a9d8533ae170809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":628},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b99500b5d364575aa94529f486a85b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":628},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995d50ed33e745ee82e7f89f3cb8c9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":832,
                  "y":628},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3affade3dc042d38225b911f3f976f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":953,
              "y":620},
            "size":{
              "width":69,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d08181c20734438acd7e58b7ea97645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":953,
                  "y":620},
                "size":{
                  "width":69,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u70.png"}},
{
          "id":"ccccfa0c5d0d49d593e7decfe7222ca3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e210bbf594b646d79cb65dda9d910bf6"},
{
          "id":"a5853cc6b4dd4939bae4a288c84a068b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":22,
              "y":680},
            "size":{
              "width":1000,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0c855f995840caadbf9c42fee6f56a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":22,
                  "y":680},
                "size":{
                  "width":1000,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u115.png"}},
{
          "id":"a390cfaec91f4591ae8091e5c2cc5587",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":657},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}}]}},
  "masters":{
    "e210bbf594b646d79cb65dda9d910bf6":{
      "packageId":"e210bbf594b646d79cb65dda9d910bf6",
      "type":"Axure:Master",
      "name":"首页头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0b5f8b0d965847b49ce3cad716d29694",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":20},
              "size":{
                "width":1000,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8904f223ac5048c0964306a8e702dc6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":20},
                  "size":{
                    "width":1000,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u73.png"}},
{
            "id":"0300ca2ed5e24fba822999e6966114f5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":45,
                "y":28},
              "size":{
                "width":105,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"136367b2b97740d0abede55f3c358248",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":45,
                    "y":28},
                  "size":{
                    "width":105,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"065cfee56a1344008866d822269ee632",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":150,
                "y":28},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5332be88bd74552bd6c501013786cfe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":150,
                    "y":28},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d776c514e1644638eb2c3dddb944263",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67c5d25a661e4e5081598453c3c0c419",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 注册",
                        "target":{
                          "targetType":"page",
                          "url":"注册.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ec9356088745466f914125b83d0bf02d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":947,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"797fe9cb417f41b0a1d1435759ae44ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":947,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6820edb8cd3b4f2b8eda469f7dd746a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":890,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"687c09c0312a41319c4ea490d5847e1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":890,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095dd3f628f448a9925b69b55420a846",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":66},
              "size":{
                "width":90,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"828b8bb639cc46d08f84699a82541e4d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":66},
                  "size":{
                    "width":90,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u85.png"}},
{
            "id":"bb30d155fe2743f19af2b129dfa85a1c",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Calibri Regular', 'Calibri'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":240,
                "y":66},
              "size":{
                "width":450,
                "height":35}},
            "adaptiveStyles":{
},
            "placeholderText":"输入你要的商品"},
{
            "id":"897372202059412db6f53a26bf13238a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":315,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f6d59042d4c4ef693f2df726c76dbef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":315,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37e213f417df49b4a8a8c341540aead8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":381,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6866144be9884105be8450f13a9dbbf0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":381,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c066360e135b4ef68d94bbdefa8198f0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":446,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f63a9b4da9742dcb01077225ab23f9b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":446,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ee9496bb5c7443708288be817aa7207d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":509,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"777b21a4dbf9458d8718ae3418fe2a73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":509,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bbe8fbe141574ba39fbe497a1464d7a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":574,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44a40a5dace044aba5fec1769c2569d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":574,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ac5782bd97204f8db3ffe2a76a40428a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"ced5511b471441988536bd1dbbdf801c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":436,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"e5c7c0e6c6e543ecbf889f6cdd299ea1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":499,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"0ebb33af9c004e8ba2c60160a6276f7c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":562,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"7d8eaf9e4741473da5f4f17b64592943",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":637,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0164289aa810432a93f13a0f28705865",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":637,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d4bb60b8434f44b986d800dbd45b619a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d209c320210a443d923a520645314026",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c5c66c9c9cd486785f7e2bda7b66f9f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":627,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"b59450d47e7a45bdbba9eafd3c3d7224",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":690,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"add258e5ce3e4cc5beb7843006521493",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":828,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"092fc3c354414906bc2cbfbe3a3b5e56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":828,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e5f74d27c40346a0afc1c26380dfb716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":760,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9abfa4e641054815ab706fa21af8d36c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":760,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b0753f75c6314766a9071776fe6ed496",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":247,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1d278c0e3ea34d27b8854df6780124ef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":247,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 宠物市场",
                        "target":{
                          "targetType":"page",
                          "url":"宠物市场.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79fd54120a5a488da340068241d34bcb",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":301,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}}]}}},
  "objectPaths":{
    "2e8a7ce66360415aba8293f06e9e28aa":{
      "scriptId":"u0"},
    "4884e921d7a447418100483377d1f2a9":{
      "scriptId":"u1"},
    "56ae56c297ed430f8d731161f42d702c":{
      "scriptId":"u2"},
    "05e2a04f7c34497780123fc0e96ebcfa":{
      "scriptId":"u3"},
    "6b66942409aa4ac1ac69995b34d0ff01":{
      "scriptId":"u4"},
    "af9efc13813c4ae5b2ab0cc70f576795":{
      "scriptId":"u5"},
    "9ad4642150dd42c39c5257f1d70de1b6":{
      "scriptId":"u6"},
    "0c3e8f587c2e4002917971234f4b0005":{
      "scriptId":"u7"},
    "fa2de4d4bb1f49f6bde6f103d1652c11":{
      "scriptId":"u8"},
    "1978bd9c22aa450cbb23c006a29cf6ff":{
      "scriptId":"u9"},
    "36c75e8ec45e4a398d6fddae777c4b8a":{
      "scriptId":"u10"},
    "fdad416234994b4d89ee5f96fdc31293":{
      "scriptId":"u11"},
    "449ca9c8ad034dd0a4350d42990a4d64":{
      "scriptId":"u12"},
    "97a0169862d646b3b4442d97241a858d":{
      "scriptId":"u13"},
    "adcbe8ff43ab48329a6cccdcd27a1f68":{
      "scriptId":"u14"},
    "05c9bee976f04cdfb3a0668d55bb496c":{
      "scriptId":"u15"},
    "7168ec6030814b7f9d0cee8d194cd8bb":{
      "scriptId":"u16"},
    "3e81c29eca2942fdad97c461e4dac8f4":{
      "scriptId":"u17"},
    "b6534e83fe064e74b559a88ad71d046c":{
      "scriptId":"u18"},
    "f9da0ab4e3f048cba861abd4d080e759":{
      "scriptId":"u19"},
    "c25d57b3f4ed408680318dc9652542d5":{
      "scriptId":"u20"},
    "d377deebcf7b42ceaaba0dc2b8b02dfe":{
      "scriptId":"u21"},
    "0c274b66f65d444dbef8e440d7568810":{
      "scriptId":"u22"},
    "66018b5a00d944ffba5447a9629bc270":{
      "scriptId":"u23"},
    "d9116d84e678495c83a54fe6b89df73c":{
      "scriptId":"u24"},
    "39451f9d18904a8788b00049e49efdbc":{
      "scriptId":"u25"},
    "4839108acea64c6ea7f2a5db3aeb4666":{
      "scriptId":"u26"},
    "2a2ca3be492d4c86927d62193ebbbda4":{
      "scriptId":"u27"},
    "f3371b55e05f47a58e8ebc43fa2d99e9":{
      "scriptId":"u28"},
    "20b77569fd5748eba41aaf8473150f42":{
      "scriptId":"u29"},
    "714b9e93954241b0bd3ada657cd7b896":{
      "scriptId":"u30"},
    "8f6f040c38cf45a2859a6792f0f4793e":{
      "scriptId":"u31"},
    "d6813c7f6ce04e79aa3a2207aa2aab0a":{
      "scriptId":"u32"},
    "243b6ce3a6224582852735a268c13317":{
      "scriptId":"u33"},
    "3df525e50ea0428aa00c13b29c89a4f7":{
      "scriptId":"u34"},
    "3c99862b3b3044a1b69bec684c6139ba":{
      "scriptId":"u35"},
    "fa04efd16828469c886377ee62cbfc51":{
      "scriptId":"u36"},
    "eff08a6b72fb48e5977686937c8d41da":{
      "scriptId":"u37"},
    "999abe1cf54f45218f9b88bf8d4e22ae":{
      "scriptId":"u38"},
    "5a11bd789103494db24e7a84aa5364d5":{
      "scriptId":"u39"},
    "1f9655d88b734aa1897d1ab6832945f8":{
      "scriptId":"u40"},
    "be722036da2d44428f2d150b00808da2":{
      "scriptId":"u41"},
    "5689494df293456694f2dd81e820d379":{
      "scriptId":"u42"},
    "5eb2b83e13a14b9885794353e95e060b":{
      "scriptId":"u43"},
    "7ce2678a8c6642a2a70d4286f4cf7372":{
      "scriptId":"u44"},
    "3bee2bd166344c368583704d2677bb97":{
      "scriptId":"u45"},
    "e2dd840484ba47adb07821cb9afcf666":{
      "scriptId":"u46"},
    "30ca4a753f6542d0a6db287856374732":{
      "scriptId":"u47"},
    "e4f4cbe3d00b47949b92512eaaf2c7f2":{
      "scriptId":"u48"},
    "96e459f55e344755addb34053a794e9c":{
      "scriptId":"u49"},
    "2d3a78626bcf4ad799086ae4ec7f9fbc":{
      "scriptId":"u50"},
    "4c9cfda627b74ec49ab9765d6674129e":{
      "scriptId":"u51"},
    "bcf123cb6cff46839115c01422628d19":{
      "scriptId":"u52"},
    "abecabf4216b4cbe8f719f451d5bcf86":{
      "scriptId":"u53"},
    "accb6ed3feba44d2a26798abf5b57284":{
      "scriptId":"u54"},
    "783dd588d2384805ae769e80b8218729":{
      "scriptId":"u55"},
    "6bc23b3331b74f1296fcff0d0a35c3e3":{
      "scriptId":"u56"},
    "a339450bb03d4f4fbdb05779ea82ac13":{
      "scriptId":"u57"},
    "153db4dc64ec4aebb094a338d81c3837":{
      "scriptId":"u58"},
    "d4d0cb1922b64b0dbec5f422d1a1e19a":{
      "scriptId":"u59"},
    "9fabe44397c3488990be9006b1d21583":{
      "scriptId":"u60"},
    "5fd0a40c2bb245f7a81f1130c86cd6b1":{
      "scriptId":"u61"},
    "9526e4b8a6db45d7ac3198f3cf5ece1a":{
      "scriptId":"u62"},
    "5979a36a019f44e691afc4ff76730463":{
      "scriptId":"u63"},
    "76f9a6aea4a348afa36e94ae1b381809":{
      "scriptId":"u64"},
    "095d467f4334439eabab460c05ad4c67":{
      "scriptId":"u65"},
    "eefa88add3cc4bd2bc3921a7f4520957":{
      "scriptId":"u66"},
    "06f90dc65a1b482d8a9d8533ae170809":{
      "scriptId":"u67"},
    "0b99500b5d364575aa94529f486a85b4":{
      "scriptId":"u68"},
    "995d50ed33e745ee82e7f89f3cb8c9bb":{
      "scriptId":"u69"},
    "d3affade3dc042d38225b911f3f976f0":{
      "scriptId":"u70"},
    "0d08181c20734438acd7e58b7ea97645":{
      "scriptId":"u71"},
    "ccccfa0c5d0d49d593e7decfe7222ca3":{
      "scriptId":"u72",
      "0b5f8b0d965847b49ce3cad716d29694":{
        "scriptId":"u73"},
      "8904f223ac5048c0964306a8e702dc6d":{
        "scriptId":"u74"},
      "0300ca2ed5e24fba822999e6966114f5":{
        "scriptId":"u75"},
      "136367b2b97740d0abede55f3c358248":{
        "scriptId":"u76"},
      "065cfee56a1344008866d822269ee632":{
        "scriptId":"u77"},
      "a5332be88bd74552bd6c501013786cfe":{
        "scriptId":"u78"},
      "5d776c514e1644638eb2c3dddb944263":{
        "scriptId":"u79"},
      "67c5d25a661e4e5081598453c3c0c419":{
        "scriptId":"u80"},
      "ec9356088745466f914125b83d0bf02d":{
        "scriptId":"u81"},
      "797fe9cb417f41b0a1d1435759ae44ab":{
        "scriptId":"u82"},
      "6820edb8cd3b4f2b8eda469f7dd746a0":{
        "scriptId":"u83"},
      "687c09c0312a41319c4ea490d5847e1d":{
        "scriptId":"u84"},
      "095dd3f628f448a9925b69b55420a846":{
        "scriptId":"u85"},
      "828b8bb639cc46d08f84699a82541e4d":{
        "scriptId":"u86"},
      "bb30d155fe2743f19af2b129dfa85a1c":{
        "scriptId":"u87"},
      "897372202059412db6f53a26bf13238a":{
        "scriptId":"u88"},
      "7f6d59042d4c4ef693f2df726c76dbef":{
        "scriptId":"u89"},
      "37e213f417df49b4a8a8c341540aead8":{
        "scriptId":"u90"},
      "6866144be9884105be8450f13a9dbbf0":{
        "scriptId":"u91"},
      "c066360e135b4ef68d94bbdefa8198f0":{
        "scriptId":"u92"},
      "2f63a9b4da9742dcb01077225ab23f9b":{
        "scriptId":"u93"},
      "ee9496bb5c7443708288be817aa7207d":{
        "scriptId":"u94"},
      "777b21a4dbf9458d8718ae3418fe2a73":{
        "scriptId":"u95"},
      "bbe8fbe141574ba39fbe497a1464d7a0":{
        "scriptId":"u96"},
      "44a40a5dace044aba5fec1769c2569d2":{
        "scriptId":"u97"},
      "ac5782bd97204f8db3ffe2a76a40428a":{
        "scriptId":"u98"},
      "ced5511b471441988536bd1dbbdf801c":{
        "scriptId":"u99"},
      "e5c7c0e6c6e543ecbf889f6cdd299ea1":{
        "scriptId":"u100"},
      "0ebb33af9c004e8ba2c60160a6276f7c":{
        "scriptId":"u101"},
      "7d8eaf9e4741473da5f4f17b64592943":{
        "scriptId":"u102"},
      "0164289aa810432a93f13a0f28705865":{
        "scriptId":"u103"},
      "d4bb60b8434f44b986d800dbd45b619a":{
        "scriptId":"u104"},
      "d209c320210a443d923a520645314026":{
        "scriptId":"u105"},
      "5c5c66c9c9cd486785f7e2bda7b66f9f":{
        "scriptId":"u106"},
      "b59450d47e7a45bdbba9eafd3c3d7224":{
        "scriptId":"u107"},
      "add258e5ce3e4cc5beb7843006521493":{
        "scriptId":"u108"},
      "092fc3c354414906bc2cbfbe3a3b5e56":{
        "scriptId":"u109"},
      "e5f74d27c40346a0afc1c26380dfb716":{
        "scriptId":"u110"},
      "9abfa4e641054815ab706fa21af8d36c":{
        "scriptId":"u111"},
      "b0753f75c6314766a9071776fe6ed496":{
        "scriptId":"u112"},
      "1d278c0e3ea34d27b8854df6780124ef":{
        "scriptId":"u113"},
      "79fd54120a5a488da340068241d34bcb":{
        "scriptId":"u114"}},
    "a5853cc6b4dd4939bae4a288c84a068b":{
      "scriptId":"u115"},
    "ef0c855f995840caadbf9c42fee6f56a":{
      "scriptId":"u116"},
    "a390cfaec91f4591ae8091e5c2cc5587":{
      "scriptId":"u117"}}});