$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1458745318468.75),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"c58cbfd5fcef4ece94e305d9a71d227d",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF00BE9C},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f979f8ad03fe4e9e90955d596e65c487",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":200,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"212b40d8207e4eec977dd9bdfeadb7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":200,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u1.png"}},
{
          "id":"d51225c68f7b43cb8172033da9502204",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":83},
            "size":{
              "width":350,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae817e274644d16b0c9586215292636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":83},
                "size":{
                  "width":350,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"c0dbf4e567d147f88e83a80ee36fc8d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":367,
              "y":93},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc403c167344d5a9d6b7495dad7d88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":367,
                  "y":93},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ab7e57c8f4741e5ac7878bf1044458e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":561,
              "y":93},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa82007d65ae4f0a93652f20833d3a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":561,
                  "y":93},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e7a041f42b84ef683e95c33a7203a19",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":140},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号"},
{
          "id":"a76c63eaeb7345929b3fff0dedaa2bef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":185},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff7b4ef4837c4265b6ee903670a05a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":185},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdfce3bef2ca404f839bea8f53f1c008",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":212},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"验证码"},
{
          "id":"389181b0a52f42dda73426e1b9604f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":212},
            "size":{
              "width":77,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26674fce18a4379b82199a4c321eaac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":527,
                  "y":212},
                "size":{
                  "width":77,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u16.png"}},
{
          "id":"ab026a5600104da0a5fbfc3cd5990bef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":614,
              "y":224},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f4236da75c4b519961144e5625ed22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":614,
                  "y":224},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3e2d3e33d9f45edbb3aee4a79133435",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":267},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"5e0b21302f214108ab8108ab4dd4505c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":264},
            "size":{
              "width":128,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5632563f23754d308a83fc6904241e6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":264},
                "size":{
                  "width":128,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u17.png"}},
{
          "id":"6fbab510e60d4c83b45bda7aa9e6056b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":327},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"密码"},
{
          "id":"3465af6d85f3412b8bfe9dc22df88e9e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":382},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"重复密码"},
{
          "id":"b029a36b82764d048179c04cd41f0e21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":450},
            "size":{
              "width":303,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ba3caf0eca4a0baa5f7dceecfc89f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":450},
                "size":{
                  "width":303,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u21.png"}},
{
          "id":"7a342116ea8947669374d4743d454dab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":505},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d0f9dbdf1b46eda713fd7401687084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":505},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25b46d967fdd472caf49703c595dfd3e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"b9581baba4264207b4237cea10d8e7d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":10,
              "y":591},
            "size":{
              "width":1000,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f338bdcd38a648f8ac00e85e4fd8f9f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":10,
                  "y":591},
                "size":{
                  "width":1000,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u115.png"}},
{
          "id":"2e97b604d7874c3aa1e8a4841373e57f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":566},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "f979f8ad03fe4e9e90955d596e65c487":{
      "scriptId":"u0"},
    "212b40d8207e4eec977dd9bdfeadb7f7":{
      "scriptId":"u1"},
    "d51225c68f7b43cb8172033da9502204":{
      "scriptId":"u2"},
    "eae817e274644d16b0c9586215292636":{
      "scriptId":"u3"},
    "c0dbf4e567d147f88e83a80ee36fc8d6":{
      "scriptId":"u4"},
    "7fc403c167344d5a9d6b7495dad7d88f":{
      "scriptId":"u5"},
    "4ab7e57c8f4741e5ac7878bf1044458e":{
      "scriptId":"u6"},
    "fa82007d65ae4f0a93652f20833d3a34":{
      "scriptId":"u7"},
    "6e7a041f42b84ef683e95c33a7203a19":{
      "scriptId":"u8"},
    "a76c63eaeb7345929b3fff0dedaa2bef":{
      "scriptId":"u9"},
    "ff7b4ef4837c4265b6ee903670a05a45":{
      "scriptId":"u10"},
    "cdfce3bef2ca404f839bea8f53f1c008":{
      "scriptId":"u11"},
    "389181b0a52f42dda73426e1b9604f2a":{
      "scriptId":"u12"},
    "e26674fce18a4379b82199a4c321eaac":{
      "scriptId":"u13"},
    "ab026a5600104da0a5fbfc3cd5990bef":{
      "scriptId":"u14"},
    "08f4236da75c4b519961144e5625ed22":{
      "scriptId":"u15"},
    "b3e2d3e33d9f45edbb3aee4a79133435":{
      "scriptId":"u16"},
    "5e0b21302f214108ab8108ab4dd4505c":{
      "scriptId":"u17"},
    "5632563f23754d308a83fc6904241e6b":{
      "scriptId":"u18"},
    "6fbab510e60d4c83b45bda7aa9e6056b":{
      "scriptId":"u19"},
    "3465af6d85f3412b8bfe9dc22df88e9e":{
      "scriptId":"u20"},
    "b029a36b82764d048179c04cd41f0e21":{
      "scriptId":"u21"},
    "33ba3caf0eca4a0baa5f7dceecfc89f1":{
      "scriptId":"u22"},
    "7a342116ea8947669374d4743d454dab":{
      "scriptId":"u23"},
    "53d0f9dbdf1b46eda713fd7401687084":{
      "scriptId":"u24"},
    "25b46d967fdd472caf49703c595dfd3e":{
      "scriptId":"u25",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u26"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u27"}},
    "b9581baba4264207b4237cea10d8e7d1":{
      "scriptId":"u28"},
    "f338bdcd38a648f8ac00e85e4fd8f9f2":{
      "scriptId":"u29"},
    "2e97b604d7874c3aa1e8a4841373e57f":{
      "scriptId":"u30"}}});