$axure.loadCurrentPage({
  "url":"找回密码.html",
  "generationDate":new Date(1458745317551.68),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"445c3264eacc4f068cf34ef8fb99273e",
    "type":"Axure:Page",
    "name":"找回密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e8f1c90abc8424090eaa80dd035c6db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"1604cc9ac38e4f6b8503b1f35bee6b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":130},
            "size":{
              "width":950,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991fb6de52ec4de5ac297e310b17c5f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":130},
                "size":{
                  "width":950,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u3.png"}},
{
          "id":"beb487656a574da48cfcc11c27e8b786",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":150},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c8efefa6bd4488b12ba33d6b752251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":150},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a58ba2dd23942d49ad3a6aa6758f9a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":710,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57baf281ed5c40638aef41f83a8ce331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":710,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u7.png"}},
{
          "id":"8e5b7a6cd56e40bbbe36eee2051e8b64",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":300},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/找回密码/u9_line.png"}},
{
          "id":"2c39613e66f846eebea3c2432362cf0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":328,
              "y":347},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13d1c2511ec6477bae67e8cedf646663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":328,
                  "y":347},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04c99a3509f04a96a2ff0d91764cedde",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":336},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e99e896bd2f64372b2449b00b2bff476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":328,
              "y":401},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4ad84618c3416abb660d40795a7eaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":328,
                  "y":401},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74e68bcd073f411c8988b102eeacc912",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":391},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"7c5c57d7f70a4bd28afda7a44de975a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":558,
              "y":390},
            "size":{
              "width":77,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3765ef24a65e410ab645b3c9c6e7d47c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":390},
                "size":{
                  "width":77,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u16.png"}},
{
          "id":"568a0b9e70324ec5b76f8f773e8cce61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":402},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a444d7450f248148ff711dd543b4a14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":402},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc8b860c17324442bf15041ca1d1c9aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":450},
            "size":{
              "width":134,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f27e372ddc4108a305e1e4d03da054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":450},
                "size":{
                  "width":134,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 验证身份",
                      "target":{
                        "targetType":"page",
                        "url":"验证身份.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/找回密码/u20.png"}},
{
          "id":"7cbd64490e77475c9e186d9acf42453a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":510},
            "size":{
              "width":391,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842690aa2d354eba849a5c355a12a1d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":510},
                "size":{
                  "width":391,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b9738980f6a4be394fc37ab59159520",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":598},
            "size":{
              "width":669,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cb76bb6981410eb3f60b8e23401ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":191,
                  "y":598},
                "size":{
                  "width":669,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38a01559613040ed993835b35f015d20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":650},
            "size":{
              "width":569,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f286e6fb9c274ce4a73277eb75cf422c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":650},
                "size":{
                  "width":569,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u26.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "1e8f1c90abc8424090eaa80dd035c6db":{
      "scriptId":"u0",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u1"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u2"}},
    "1604cc9ac38e4f6b8503b1f35bee6b0e":{
      "scriptId":"u3"},
    "991fb6de52ec4de5ac297e310b17c5f3":{
      "scriptId":"u4"},
    "beb487656a574da48cfcc11c27e8b786":{
      "scriptId":"u5"},
    "f3c8efefa6bd4488b12ba33d6b752251":{
      "scriptId":"u6"},
    "2a58ba2dd23942d49ad3a6aa6758f9a7":{
      "scriptId":"u7"},
    "57baf281ed5c40638aef41f83a8ce331":{
      "scriptId":"u8"},
    "8e5b7a6cd56e40bbbe36eee2051e8b64":{
      "scriptId":"u9"},
    "2c39613e66f846eebea3c2432362cf0a":{
      "scriptId":"u10"},
    "13d1c2511ec6477bae67e8cedf646663":{
      "scriptId":"u11"},
    "04c99a3509f04a96a2ff0d91764cedde":{
      "scriptId":"u12"},
    "e99e896bd2f64372b2449b00b2bff476":{
      "scriptId":"u13"},
    "4e4ad84618c3416abb660d40795a7eaa":{
      "scriptId":"u14"},
    "74e68bcd073f411c8988b102eeacc912":{
      "scriptId":"u15"},
    "7c5c57d7f70a4bd28afda7a44de975a5":{
      "scriptId":"u16"},
    "3765ef24a65e410ab645b3c9c6e7d47c":{
      "scriptId":"u17"},
    "568a0b9e70324ec5b76f8f773e8cce61":{
      "scriptId":"u18"},
    "0a444d7450f248148ff711dd543b4a14":{
      "scriptId":"u19"},
    "fc8b860c17324442bf15041ca1d1c9aa":{
      "scriptId":"u20"},
    "65f27e372ddc4108a305e1e4d03da054":{
      "scriptId":"u21"},
    "7cbd64490e77475c9e186d9acf42453a":{
      "scriptId":"u22"},
    "842690aa2d354eba849a5c355a12a1d9":{
      "scriptId":"u23"},
    "2b9738980f6a4be394fc37ab59159520":{
      "scriptId":"u24"},
    "41cb76bb6981410eb3f60b8e23401ee0":{
      "scriptId":"u25"},
    "38a01559613040ed993835b35f015d20":{
      "scriptId":"u26"},
    "f286e6fb9c274ce4a73277eb75cf422c":{
      "scriptId":"u27"}}});