$axure.loadCurrentPage({
  "url":"商品页.html",
  "generationDate":new Date(1458745317422.78),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"3d3bae5bf9b1443f9b216a5b81526122",
    "type":"Axure:Page",
    "name":"商品页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d82dc8368e6c416891d1e7f03ef85df9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"e210bbf594b646d79cb65dda9d910bf6"},
{
          "id":"197ec4fffa6e44b48e8c59ae96580bc6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c5ce87fb4cd6485da0a6a50c06bde6c1"},
{
          "id":"503236669f024797938116bd4ba1435d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":137},
            "size":{
              "width":350,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb50633f1699492ab650407e10e40d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":137},
                "size":{
                  "width":350,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u19.png"}},
{
          "id":"680277a819584678bf830215f22b169a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":400,
              "y":137},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706e4184b6994b5fbe519aef8969a8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":400,
                  "y":137},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c91eba4496004b988be3707778b58d60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":390,
              "y":170},
            "size":{
              "width":370,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4febc3fdf954c9099f8b029f3e08a33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":390,
                  "y":170},
                "size":{
                  "width":370,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u59.png"}},
{
          "id":"8af5f86936c846bcbdaf9d1cfce95e6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":180},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2bff10ff4e4a1185d072c5e657614b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":180},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7261fbc9fd33453881ff40ffed5aacef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":180},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2216e697a8934a2188c4193f9428c7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":180},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"257318284fa341f19747cd892267093f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":206},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b07d5cf6b1450f82f39ddd2f7c89d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":206},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e51604199e8466eafa5639dc8024ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":206},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51badfa9e071436b881ae28aa422f14b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":206},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"958dc1d37ce74f52be88718afadd069a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":241},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3303e47c6214b9fb48f46665e82de0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":241},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"262a81a7549c4685b3027ec68b06a009",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":241},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14c0df098824399bdb66fbb971c442a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":241},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dfbd34509ce4091af25e394f5ae3b00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":257},
            "size":{
              "width":370,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品页/u73_line.png"}},
{
          "id":"bb9abbbd96b34e089bddc26fe72cc5eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":273},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5e710021f0642d197a90dfb7963a2e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":273},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3deed815e8c64105bd0811257e279842",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":293},
            "size":{
              "width":370,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品页/u73_line.png"}},
{
          "id":"6718cfce806e498f80a37e04ba12cca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":272},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265ddc623bc94f1c9dea67288e55e80d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":272},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b8546a8c52442478315a376aa7c1180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":320},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9804cf3b9e84df2abbc508009772b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":320},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baafc608f0ae447f87aa60bacbf949cc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":320},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"79f391bf8b3e40d18be8f2793754e859",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":320},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"690d81f8be2542528a98aa2cab6c8cba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":320},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051d3fd6af5443ed825172e1edda8800",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":360},
            "size":{
              "width":180,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdcf2f892c514a7eb402aa35f0db73bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":360},
                "size":{
                  "width":180,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单确定页",
                      "target":{
                        "targetType":"page",
                        "url":"订单确定页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品页/u84.png"}},
{
          "id":"b7fe0f9ee1994f44ae09ed0b010a503c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":360},
            "size":{
              "width":180,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a015193e4df461baa160ba5e424421f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":583,
                  "y":360},
                "size":{
                  "width":180,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品页/u86.png"}},
{
          "id":"fafdf9d9ea5c46569e3797cc18bb57e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":460},
            "size":{
              "width":52,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b015a6627b74ad4817cc26e80dccd77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":460},
                "size":{
                  "width":52,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u88.png"}},
{
          "id":"fd869c65e15343bf8303823ac81358c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":460},
            "size":{
              "width":133,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8494e713e73c4652a28515376eba1140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":460},
                "size":{
                  "width":133,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u90.png"}},
{
          "id":"c5e3f30cfaf7435db88d3f478ed72db5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":463},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"483165b81a134b9cb43ad205a37841b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":463},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u92.png"}},
{
          "id":"c839edbdcf574dd7a299aaf16831276a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":463},
            "size":{
              "width":53,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6020b1c05346a1afef7b3aa6b9c0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":463},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u94.png"}},
{
          "id":"d5d0db7c4634469c9a6b1537c0ae4792",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":463},
            "size":{
              "width":50,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1770a3495fae4102a68a538593aa64a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":463},
                "size":{
                  "width":50,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u96.png"}},
{
          "id":"68b937ab35024bac97f0f4c391a39e9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":464},
            "size":{
              "width":51,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13c356dffbdd41479eca1cb0f087786f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":464},
                "size":{
                  "width":51,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u98.png"}},
{
          "id":"96dc3a0ae6404bb49f54ec96251a9700",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":462},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795a318f27654da4bddfe1a18d654d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":462},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u100.png"}},
{
          "id":"71dfa7a4bb104ddc959a136e6ec65b86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":681,
              "y":464},
            "size":{
              "width":55,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2559e1d140d421dbef7fb3247c4b695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":681,
                  "y":464},
                "size":{
                  "width":55,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u102.png"}},
{
          "id":"61ad1c9dc8a44f1093dfaff80edecda9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":464},
            "size":{
              "width":86,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aecdf7767cb64435b191a27c37d54711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":464},
                "size":{
                  "width":86,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u104.png"}},
{
          "id":"7f09c86a8a5346628958766392d5f255",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":495},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488085acd36842f99878ab8bb5dcdf9e",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16330b5cd9f348818de8329feca8d98d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f14a6c8b8954674a73c8df814955b93",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/累计评论/u2.png"}},
{
                  "id":"4c6940a16bcf469986d73d129a852ab2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f0596c4771546a5884f5e2933abaad8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/累计评论/u4.png"}}]}]},
{
          "id":"3815750f1ce64ac0992577175646fe58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":30,
              "y":525},
            "size":{
              "width":770,
              "height":216}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64783a0ffccc4f21926ea8f5ebfe879f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":30,
                  "y":525},
                "size":{
                  "width":770,
                  "height":216}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品页/u112.png"}},
{
          "id":"043687a183fe48e5be9a9fcc9ae1b668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":535},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d0a2131cf94b63a80dc09272d6dcd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":535},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86beafb13c5549688abcb0f255110446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":535},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d921404273a414490f60a30acaa16cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":535},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e548d25175745d2a8f1a8edd1398238",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":560},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea47165f97164355988e9bdfc9e56436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":560},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b46697fc219443a58c1ccbf350a0312d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":584},
            "size":{
              "width":740,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089cf17dae4e4ab8911479ed1d70de9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":584},
                "size":{
                  "width":740,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9808fd60e80443e8af952062b2b8455",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":24,
              "y":780},
            "size":{
              "width":1000,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408a6e42c3e1459ebd8a90087b359ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":24,
                  "y":780},
                "size":{
                  "width":1000,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u115.png"}},
{
          "id":"04e556419e964077890fcad08b0d096d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":755},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}}]}},
  "masters":{
    "e210bbf594b646d79cb65dda9d910bf6":{
      "packageId":"e210bbf594b646d79cb65dda9d910bf6",
      "type":"Axure:Master",
      "name":"首页头部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0b5f8b0d965847b49ce3cad716d29694",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":20},
              "size":{
                "width":1000,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8904f223ac5048c0964306a8e702dc6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":20},
                  "size":{
                    "width":1000,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u73.png"}},
{
            "id":"0300ca2ed5e24fba822999e6966114f5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":45,
                "y":28},
              "size":{
                "width":105,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"136367b2b97740d0abede55f3c358248",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":45,
                    "y":28},
                  "size":{
                    "width":105,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"065cfee56a1344008866d822269ee632",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":150,
                "y":28},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5332be88bd74552bd6c501013786cfe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":150,
                    "y":28},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d776c514e1644638eb2c3dddb944263",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67c5d25a661e4e5081598453c3c0c419",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 注册",
                        "target":{
                          "targetType":"page",
                          "url":"注册.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ec9356088745466f914125b83d0bf02d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":947,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"797fe9cb417f41b0a1d1435759ae44ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":947,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6820edb8cd3b4f2b8eda469f7dd746a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":890,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"687c09c0312a41319c4ea490d5847e1d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":890,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095dd3f628f448a9925b69b55420a846",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":689,
                "y":66},
              "size":{
                "width":90,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"828b8bb639cc46d08f84699a82541e4d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":689,
                    "y":66},
                  "size":{
                    "width":90,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u85.png"}},
{
            "id":"bb30d155fe2743f19af2b129dfa85a1c",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Calibri Regular', 'Calibri'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":240,
                "y":66},
              "size":{
                "width":450,
                "height":35}},
            "adaptiveStyles":{
},
            "placeholderText":"输入你要的商品"},
{
            "id":"897372202059412db6f53a26bf13238a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":315,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f6d59042d4c4ef693f2df726c76dbef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":315,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37e213f417df49b4a8a8c341540aead8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":381,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6866144be9884105be8450f13a9dbbf0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":381,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c066360e135b4ef68d94bbdefa8198f0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":446,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f63a9b4da9742dcb01077225ab23f9b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":446,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ee9496bb5c7443708288be817aa7207d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":509,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"777b21a4dbf9458d8718ae3418fe2a73",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":509,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bbe8fbe141574ba39fbe497a1464d7a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":574,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44a40a5dace044aba5fec1769c2569d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":574,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ac5782bd97204f8db3ffe2a76a40428a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"ced5511b471441988536bd1dbbdf801c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":436,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"e5c7c0e6c6e543ecbf889f6cdd299ea1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":499,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"0ebb33af9c004e8ba2c60160a6276f7c",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":562,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"7d8eaf9e4741473da5f4f17b64592943",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":637,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0164289aa810432a93f13a0f28705865",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":637,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d4bb60b8434f44b986d800dbd45b619a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":700,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d209c320210a443d923a520645314026",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":700,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c5c66c9c9cd486785f7e2bda7b66f9f",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":627,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"b59450d47e7a45bdbba9eafd3c3d7224",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":690,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}},
{
            "id":"add258e5ce3e4cc5beb7843006521493",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":828,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"092fc3c354414906bc2cbfbe3a3b5e56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":828,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e5f74d27c40346a0afc1c26380dfb716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":760,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9abfa4e641054815ab706fa21af8d36c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":760,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b0753f75c6314766a9071776fe6ed496",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":247,
                "y":111},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1d278c0e3ea34d27b8854df6780124ef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":247,
                    "y":111},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 宠物市场",
                        "target":{
                          "targetType":"page",
                          "url":"宠物市场.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"79fd54120a5a488da340068241d34bcb",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":301,
                "y":111},
              "size":{
                "width":10,
                "height":16}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/购物车/u98_line.png"}}]}},
    "c5ce87fb4cd6485da0a6a50c06bde6c1":{
      "packageId":"c5ce87fb4cd6485da0a6a50c06bde6c1",
      "type":"Axure:Master",
      "name":"尾部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c62214b8b3054dbea6e3dd79cddd9702",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":1405},
              "size":{
                "width":1000,
                "height":10},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/商品页/u44_line.png"}},
{
            "id":"a67d4b88a56a49e594399a38f181bb52",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":1429},
              "size":{
                "width":250,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4fdfb1de5584f33949b9254f0b7c03b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":1429},
                  "size":{
                    "width":250,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商品页/u45.png"}},
{
            "id":"09ee3f8d8f2f448b9eced0d32245e7d1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":287,
                "y":1441},
              "size":{
                "width":255,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d466e05fe1cb48428881b518baf85113",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":287,
                    "y":1441},
                  "size":{
                    "width":255,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商品页/u47.png"}},
{
            "id":"905f2fe9a2cf4baa8fed65d1c24b0911",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":564,
                "y":1431},
              "size":{
                "width":275,
                "height":74}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ec6f0d451371461bbd095dd1f5712d59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":564,
                    "y":1431},
                  "size":{
                    "width":275,
                    "height":74}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商品页/u49.png"}},
{
            "id":"71b65c24e4b24986a7b52decae8c7aba",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":845,
                "y":1429},
              "size":{
                "width":207,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87cf95d379694273809dddb119691372",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":845,
                    "y":1429},
                  "size":{
                    "width":207,
                    "height":68}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商品页/u51.png"}},
{
            "id":"3329f37ec36048039e586f8f92e24dea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "verticalAlignment":"top",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "location":{
                "x":20,
                "y":1519},
              "size":{
                "width":1000,
                "height":121}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"928020bc7b98477db3973fcd7876cee3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "verticalAlignment":"top",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "location":{
                    "x":20,
                    "y":1519},
                  "size":{
                    "width":1000,
                    "height":121}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/商品页/u53.png"}}]}}},
  "objectPaths":{
    "d82dc8368e6c416891d1e7f03ef85df9":{
      "scriptId":"u0",
      "0b5f8b0d965847b49ce3cad716d29694":{
        "scriptId":"u1"},
      "8904f223ac5048c0964306a8e702dc6d":{
        "scriptId":"u2"},
      "0300ca2ed5e24fba822999e6966114f5":{
        "scriptId":"u3"},
      "136367b2b97740d0abede55f3c358248":{
        "scriptId":"u4"},
      "065cfee56a1344008866d822269ee632":{
        "scriptId":"u5"},
      "a5332be88bd74552bd6c501013786cfe":{
        "scriptId":"u6"},
      "5d776c514e1644638eb2c3dddb944263":{
        "scriptId":"u7"},
      "67c5d25a661e4e5081598453c3c0c419":{
        "scriptId":"u8"},
      "ec9356088745466f914125b83d0bf02d":{
        "scriptId":"u9"},
      "797fe9cb417f41b0a1d1435759ae44ab":{
        "scriptId":"u10"},
      "6820edb8cd3b4f2b8eda469f7dd746a0":{
        "scriptId":"u11"},
      "687c09c0312a41319c4ea490d5847e1d":{
        "scriptId":"u12"},
      "095dd3f628f448a9925b69b55420a846":{
        "scriptId":"u13"},
      "828b8bb639cc46d08f84699a82541e4d":{
        "scriptId":"u14"},
      "bb30d155fe2743f19af2b129dfa85a1c":{
        "scriptId":"u15"},
      "897372202059412db6f53a26bf13238a":{
        "scriptId":"u16"},
      "7f6d59042d4c4ef693f2df726c76dbef":{
        "scriptId":"u17"},
      "37e213f417df49b4a8a8c341540aead8":{
        "scriptId":"u18"},
      "6866144be9884105be8450f13a9dbbf0":{
        "scriptId":"u19"},
      "c066360e135b4ef68d94bbdefa8198f0":{
        "scriptId":"u20"},
      "2f63a9b4da9742dcb01077225ab23f9b":{
        "scriptId":"u21"},
      "ee9496bb5c7443708288be817aa7207d":{
        "scriptId":"u22"},
      "777b21a4dbf9458d8718ae3418fe2a73":{
        "scriptId":"u23"},
      "bbe8fbe141574ba39fbe497a1464d7a0":{
        "scriptId":"u24"},
      "44a40a5dace044aba5fec1769c2569d2":{
        "scriptId":"u25"},
      "ac5782bd97204f8db3ffe2a76a40428a":{
        "scriptId":"u26"},
      "ced5511b471441988536bd1dbbdf801c":{
        "scriptId":"u27"},
      "e5c7c0e6c6e543ecbf889f6cdd299ea1":{
        "scriptId":"u28"},
      "0ebb33af9c004e8ba2c60160a6276f7c":{
        "scriptId":"u29"},
      "7d8eaf9e4741473da5f4f17b64592943":{
        "scriptId":"u30"},
      "0164289aa810432a93f13a0f28705865":{
        "scriptId":"u31"},
      "d4bb60b8434f44b986d800dbd45b619a":{
        "scriptId":"u32"},
      "d209c320210a443d923a520645314026":{
        "scriptId":"u33"},
      "5c5c66c9c9cd486785f7e2bda7b66f9f":{
        "scriptId":"u34"},
      "b59450d47e7a45bdbba9eafd3c3d7224":{
        "scriptId":"u35"},
      "add258e5ce3e4cc5beb7843006521493":{
        "scriptId":"u36"},
      "092fc3c354414906bc2cbfbe3a3b5e56":{
        "scriptId":"u37"},
      "e5f74d27c40346a0afc1c26380dfb716":{
        "scriptId":"u38"},
      "9abfa4e641054815ab706fa21af8d36c":{
        "scriptId":"u39"},
      "b0753f75c6314766a9071776fe6ed496":{
        "scriptId":"u40"},
      "1d278c0e3ea34d27b8854df6780124ef":{
        "scriptId":"u41"},
      "79fd54120a5a488da340068241d34bcb":{
        "scriptId":"u42"}},
    "197ec4fffa6e44b48e8c59ae96580bc6":{
      "scriptId":"u43",
      "c62214b8b3054dbea6e3dd79cddd9702":{
        "scriptId":"u44"},
      "a67d4b88a56a49e594399a38f181bb52":{
        "scriptId":"u45"},
      "d4fdfb1de5584f33949b9254f0b7c03b":{
        "scriptId":"u46"},
      "09ee3f8d8f2f448b9eced0d32245e7d1":{
        "scriptId":"u47"},
      "d466e05fe1cb48428881b518baf85113":{
        "scriptId":"u48"},
      "905f2fe9a2cf4baa8fed65d1c24b0911":{
        "scriptId":"u49"},
      "ec6f0d451371461bbd095dd1f5712d59":{
        "scriptId":"u50"},
      "71b65c24e4b24986a7b52decae8c7aba":{
        "scriptId":"u51"},
      "87cf95d379694273809dddb119691372":{
        "scriptId":"u52"},
      "3329f37ec36048039e586f8f92e24dea":{
        "scriptId":"u53"},
      "928020bc7b98477db3973fcd7876cee3":{
        "scriptId":"u54"}},
    "503236669f024797938116bd4ba1435d":{
      "scriptId":"u55"},
    "eb50633f1699492ab650407e10e40d2f":{
      "scriptId":"u56"},
    "680277a819584678bf830215f22b169a":{
      "scriptId":"u57"},
    "706e4184b6994b5fbe519aef8969a8b4":{
      "scriptId":"u58"},
    "c91eba4496004b988be3707778b58d60":{
      "scriptId":"u59"},
    "d4febc3fdf954c9099f8b029f3e08a33":{
      "scriptId":"u60"},
    "8af5f86936c846bcbdaf9d1cfce95e6b":{
      "scriptId":"u61"},
    "ca2bff10ff4e4a1185d072c5e657614b":{
      "scriptId":"u62"},
    "7261fbc9fd33453881ff40ffed5aacef":{
      "scriptId":"u63"},
    "2216e697a8934a2188c4193f9428c7cc":{
      "scriptId":"u64"},
    "257318284fa341f19747cd892267093f":{
      "scriptId":"u65"},
    "b8b07d5cf6b1450f82f39ddd2f7c89d6":{
      "scriptId":"u66"},
    "0e51604199e8466eafa5639dc8024ace":{
      "scriptId":"u67"},
    "51badfa9e071436b881ae28aa422f14b":{
      "scriptId":"u68"},
    "958dc1d37ce74f52be88718afadd069a":{
      "scriptId":"u69"},
    "e3303e47c6214b9fb48f46665e82de0c":{
      "scriptId":"u70"},
    "262a81a7549c4685b3027ec68b06a009":{
      "scriptId":"u71"},
    "c14c0df098824399bdb66fbb971c442a":{
      "scriptId":"u72"},
    "4dfbd34509ce4091af25e394f5ae3b00":{
      "scriptId":"u73"},
    "bb9abbbd96b34e089bddc26fe72cc5eb":{
      "scriptId":"u74"},
    "f5e710021f0642d197a90dfb7963a2e8":{
      "scriptId":"u75"},
    "3deed815e8c64105bd0811257e279842":{
      "scriptId":"u76"},
    "6718cfce806e498f80a37e04ba12cca4":{
      "scriptId":"u77"},
    "265ddc623bc94f1c9dea67288e55e80d":{
      "scriptId":"u78"},
    "2b8546a8c52442478315a376aa7c1180":{
      "scriptId":"u79"},
    "c9804cf3b9e84df2abbc508009772b22":{
      "scriptId":"u80"},
    "baafc608f0ae447f87aa60bacbf949cc":{
      "scriptId":"u81"},
    "79f391bf8b3e40d18be8f2793754e859":{
      "scriptId":"u82"},
    "690d81f8be2542528a98aa2cab6c8cba":{
      "scriptId":"u83"},
    "051d3fd6af5443ed825172e1edda8800":{
      "scriptId":"u84"},
    "bdcf2f892c514a7eb402aa35f0db73bf":{
      "scriptId":"u85"},
    "b7fe0f9ee1994f44ae09ed0b010a503c":{
      "scriptId":"u86"},
    "3a015193e4df461baa160ba5e424421f":{
      "scriptId":"u87"},
    "fafdf9d9ea5c46569e3797cc18bb57e7":{
      "scriptId":"u88"},
    "4b015a6627b74ad4817cc26e80dccd77":{
      "scriptId":"u89"},
    "fd869c65e15343bf8303823ac81358c7":{
      "scriptId":"u90"},
    "8494e713e73c4652a28515376eba1140":{
      "scriptId":"u91"},
    "c5e3f30cfaf7435db88d3f478ed72db5":{
      "scriptId":"u92"},
    "483165b81a134b9cb43ad205a37841b1":{
      "scriptId":"u93"},
    "c839edbdcf574dd7a299aaf16831276a":{
      "scriptId":"u94"},
    "fd6020b1c05346a1afef7b3aa6b9c0cd":{
      "scriptId":"u95"},
    "d5d0db7c4634469c9a6b1537c0ae4792":{
      "scriptId":"u96"},
    "1770a3495fae4102a68a538593aa64a1":{
      "scriptId":"u97"},
    "68b937ab35024bac97f0f4c391a39e9b":{
      "scriptId":"u98"},
    "13c356dffbdd41479eca1cb0f087786f":{
      "scriptId":"u99"},
    "96dc3a0ae6404bb49f54ec96251a9700":{
      "scriptId":"u100"},
    "795a318f27654da4bddfe1a18d654d2a":{
      "scriptId":"u101"},
    "71dfa7a4bb104ddc959a136e6ec65b86":{
      "scriptId":"u102"},
    "b2559e1d140d421dbef7fb3247c4b695":{
      "scriptId":"u103"},
    "61ad1c9dc8a44f1093dfaff80edecda9":{
      "scriptId":"u104"},
    "aecdf7767cb64435b191a27c37d54711":{
      "scriptId":"u105"},
    "7f09c86a8a5346628958766392d5f255":{
      "scriptId":"u106"},
    "488085acd36842f99878ab8bb5dcdf9e":{
      "scriptId":"u107"},
    "16330b5cd9f348818de8329feca8d98d":{
      "scriptId":"u108"},
    "8f14a6c8b8954674a73c8df814955b93":{
      "scriptId":"u109"},
    "4c6940a16bcf469986d73d129a852ab2":{
      "scriptId":"u110"},
    "5f0596c4771546a5884f5e2933abaad8":{
      "scriptId":"u111"},
    "3815750f1ce64ac0992577175646fe58":{
      "scriptId":"u112"},
    "64783a0ffccc4f21926ea8f5ebfe879f":{
      "scriptId":"u113"},
    "043687a183fe48e5be9a9fcc9ae1b668":{
      "scriptId":"u114"},
    "22d0a2131cf94b63a80dc09272d6dcd5":{
      "scriptId":"u115"},
    "86beafb13c5549688abcb0f255110446":{
      "scriptId":"u116"},
    "9d921404273a414490f60a30acaa16cc":{
      "scriptId":"u117"},
    "6e548d25175745d2a8f1a8edd1398238":{
      "scriptId":"u118"},
    "ea47165f97164355988e9bdfc9e56436":{
      "scriptId":"u119"},
    "b46697fc219443a58c1ccbf350a0312d":{
      "scriptId":"u120"},
    "089cf17dae4e4ab8911479ed1d70de9e":{
      "scriptId":"u121"},
    "c9808fd60e80443e8af952062b2b8455":{
      "scriptId":"u122"},
    "408a6e42c3e1459ebd8a90087b359ed3":{
      "scriptId":"u123"},
    "04e556419e964077890fcad08b0d096d":{
      "scriptId":"u124"}}});