$axure.loadCurrentPage({
  "url":"个人信息.html",
  "generationDate":new Date(1458745316313.34),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"3a68ac1f751d491aac2e9c299cb6d2c3",
    "type":"Axure:Page",
    "name":"个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41e845afba774c84b634821186051569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":65},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ca1dd0995e8473b92cfcd83b7f7996b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":65},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u0.png"}},
{
          "id":"acdfff64283b4ac787e1eee125a2a826",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":34},
            "size":{
              "width":600,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u2_line.png"}},
{
          "id":"7ab9ffb1827743d3bfc546af9c1b9056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":105},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe4940a07b0407db1c0e4b66cff9271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":105},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e898e04e6014e04af52b50d0c94dc3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":105},
            "size":{
              "width":83,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea424b0991d4ffd86dd38c4dae7fd7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":105},
                "size":{
                  "width":83,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u5.png"}},
{
          "id":"5893e072bdbf447f810fe4a32823ea22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":221},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78ae3a7db06469580abc6aa6a325d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":221},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e271379af46e4a2291b62769c72ee5b0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":217},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"15963397ef2f4c21a0b95e006b42a2c8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":271},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6c15181a2d44df2a701b9a6d89ec8fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":278},
            "size":{
              "width":75,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1120cc8982d9470c81fef5ff23b20832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":278},
                "size":{
                  "width":75,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5277ce860ca146e6a28d15493f747ba5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":321},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca656bd94d94dd8a3fd2dd192eadacd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":321},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ff821ef6a784a888793bb5c1795ff3b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":321},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7c47260335d44be9b201d7713d1eb71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":321},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c6835c28431b4e6487231e99416bb147",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":321},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85e1446ad3854c91b27dbbc7618c3422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":321},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"955767e138ed47d2be5dc396559b9c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":361},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef070db43fad4ce88826d3d773a88e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":361},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a2aedb1cfe4ab48d89bf2bd2681461",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":355},
            "size":{
              "width":45,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5e9116033b7845678f7bfba3331262c5",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":355},
            "size":{
              "width":45,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"04ce3eaf8713498ebe6c1794fb730b7d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":355},
            "size":{
              "width":45,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5b87d418f87b46f3a95883dd45e8a952",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":401},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b531e44e3c4d1eb329d476440c5c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":401},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ba4158735b84f6d884dcce78a8ecfa1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":398},
            "size":{
              "width":135,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8d035d67522847f786c9532f1b33675c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":398},
            "size":{
              "width":45,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e2ad09637c6c497ca1f25d1d0760cfea",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":398},
            "size":{
              "width":45,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"503d8cae64ee4e05a107f123a7f83df5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":441},
            "size":{
              "width":600,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u2_line.png"}},
{
          "id":"43f5fef428bb43db83c473347d840107",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":461},
            "size":{
              "width":48,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6a23efab804882afcbe3b79b90c750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":461},
                "size":{
                  "width":48,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人信息/u30.png"}},
{
          "id":"c09875d9dd2b447abcf6e7828c59869c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4397116251964359abe28122c080b730"},
{
          "id":"e138a44e8be7497986cd3504d506f7ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":10,
              "y":526},
            "size":{
              "width":1000,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"855162e9482a4c2d96d73d96bbb81445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":10,
                  "y":526},
                "size":{
                  "width":1000,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u115.png"}},
{
          "id":"86eff52b62f848c38616516302249de8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":506},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}}]}},
  "masters":{
    "4397116251964359abe28122c080b730":{
      "packageId":"4397116251964359abe28122c080b730",
      "type":"Axure:Master",
      "name":"我的交易导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d6bae1435ac64978b446d8da6c9890e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":64},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"575ecfba3c76482bba28b1c92b316e62",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":64},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"88e59cc71b87446382899684702a8e39",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":188},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13060b7507004e978062320e7975f9f5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":188},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"43e8339df3df494e899ca4a2f8eb000c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":228},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3efed88057734568a46b853096ec6677",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":228},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 评价管理",
                        "target":{
                          "targetType":"page",
                          "url":"评价管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"b6cb9ed2de9d4042ac9fea2a30e5f4df",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":104},
              "size":{
                "width":160,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b47d65e3530f45fd96e04c3212fee2c9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":104},
                  "size":{
                    "width":160,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的宝贝",
                        "target":{
                          "targetType":"page",
                          "url":"我的宝贝.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u39.png"}},
{
            "id":"151837040d954abe95564b6b2d75ff88",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":268},
              "size":{
                "width":160,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ee8aa69f240416ca26b231cfc7751cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":268},
                  "size":{
                    "width":160,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u41.png"}},
{
            "id":"143e85ac2680410493433cb7af8feac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":304},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a28d91536924bcabb46b8e63c6628b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":304},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"2c088a37820542e4b6c54d17cb8a1f73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":344},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"22a2236b019f4c0d85f9bf6c9810663f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":344},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"025588abdc544956a1507208746c67b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":148},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"929389a7a1e94f048aad52ebbc6b80b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":148},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 收货地址",
                        "target":{
                          "targetType":"page",
                          "url":"收货地址.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"6e83054ac4a3422f9a8907994a05b198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":20},
              "size":{
                "width":1000,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b8a703289123470b9899232ca7ac5f8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":20},
                  "size":{
                    "width":1000,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u73.png"}},
{
            "id":"e642186ef4914604b5f6a769fcf6e9dc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":28},
              "size":{
                "width":105,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ed98a9773434025a315b824c2ebb580",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":28},
                  "size":{
                    "width":105,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2748d776f31e4baf9358fbcad480b385",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":28},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1eb11f117f454f8d825850d53e8b5584",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":28},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"377c4c27a8aa4618b186212187b48cd9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d541ed5db5d4f03bde40cca5c64cffa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 注册",
                        "target":{
                          "targetType":"page",
                          "url":"注册.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9222f31d50c2419e82ddef78ab2cf9ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":944,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8664c47e4af34fce8e1e2ffc339afe1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":944,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c970c23b3ce49bca3430c587e0af62b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":887,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"404e561ae5a74471aebe7b8cd7315ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":887,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"33dd475d1b7c401fb4db8c79396f9572",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":825,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4a61fee1913411a9213ab8bff0e50b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":825,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a75f8ffb1bdd498e80585c90dd9254d3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52175b85fd3f4d72959d8d3115f5bdac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":757,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "41e845afba774c84b634821186051569":{
      "scriptId":"u0"},
    "1ca1dd0995e8473b92cfcd83b7f7996b":{
      "scriptId":"u1"},
    "acdfff64283b4ac787e1eee125a2a826":{
      "scriptId":"u2"},
    "7ab9ffb1827743d3bfc546af9c1b9056":{
      "scriptId":"u3"},
    "dfe4940a07b0407db1c0e4b66cff9271":{
      "scriptId":"u4"},
    "2e898e04e6014e04af52b50d0c94dc3c":{
      "scriptId":"u5"},
    "bea424b0991d4ffd86dd38c4dae7fd7a":{
      "scriptId":"u6"},
    "5893e072bdbf447f810fe4a32823ea22":{
      "scriptId":"u7"},
    "d78ae3a7db06469580abc6aa6a325d13":{
      "scriptId":"u8"},
    "e271379af46e4a2291b62769c72ee5b0":{
      "scriptId":"u9"},
    "15963397ef2f4c21a0b95e006b42a2c8":{
      "scriptId":"u10"},
    "b6c15181a2d44df2a701b9a6d89ec8fb":{
      "scriptId":"u11"},
    "1120cc8982d9470c81fef5ff23b20832":{
      "scriptId":"u12"},
    "5277ce860ca146e6a28d15493f747ba5":{
      "scriptId":"u13"},
    "8ca656bd94d94dd8a3fd2dd192eadacd":{
      "scriptId":"u14"},
    "3ff821ef6a784a888793bb5c1795ff3b":{
      "scriptId":"u15"},
    "c7c47260335d44be9b201d7713d1eb71":{
      "scriptId":"u16"},
    "c6835c28431b4e6487231e99416bb147":{
      "scriptId":"u17"},
    "85e1446ad3854c91b27dbbc7618c3422":{
      "scriptId":"u18"},
    "955767e138ed47d2be5dc396559b9c28":{
      "scriptId":"u19"},
    "ef070db43fad4ce88826d3d773a88e55":{
      "scriptId":"u20"},
    "c9a2aedb1cfe4ab48d89bf2bd2681461":{
      "scriptId":"u21"},
    "5e9116033b7845678f7bfba3331262c5":{
      "scriptId":"u22"},
    "04ce3eaf8713498ebe6c1794fb730b7d":{
      "scriptId":"u23"},
    "5b87d418f87b46f3a95883dd45e8a952":{
      "scriptId":"u24"},
    "66b531e44e3c4d1eb329d476440c5c05":{
      "scriptId":"u25"},
    "8ba4158735b84f6d884dcce78a8ecfa1":{
      "scriptId":"u26"},
    "8d035d67522847f786c9532f1b33675c":{
      "scriptId":"u27"},
    "e2ad09637c6c497ca1f25d1d0760cfea":{
      "scriptId":"u28"},
    "503d8cae64ee4e05a107f123a7f83df5":{
      "scriptId":"u29"},
    "43f5fef428bb43db83c473347d840107":{
      "scriptId":"u30"},
    "9b6a23efab804882afcbe3b79b90c750":{
      "scriptId":"u31"},
    "c09875d9dd2b447abcf6e7828c59869c":{
      "scriptId":"u32",
      "d6bae1435ac64978b446d8da6c9890e8":{
        "scriptId":"u33"},
      "575ecfba3c76482bba28b1c92b316e62":{
        "scriptId":"u34"},
      "88e59cc71b87446382899684702a8e39":{
        "scriptId":"u35"},
      "13060b7507004e978062320e7975f9f5":{
        "scriptId":"u36"},
      "43e8339df3df494e899ca4a2f8eb000c":{
        "scriptId":"u37"},
      "3efed88057734568a46b853096ec6677":{
        "scriptId":"u38"},
      "b6cb9ed2de9d4042ac9fea2a30e5f4df":{
        "scriptId":"u39"},
      "b47d65e3530f45fd96e04c3212fee2c9":{
        "scriptId":"u40"},
      "151837040d954abe95564b6b2d75ff88":{
        "scriptId":"u41"},
      "3ee8aa69f240416ca26b231cfc7751cf":{
        "scriptId":"u42"},
      "143e85ac2680410493433cb7af8feac9":{
        "scriptId":"u43"},
      "7a28d91536924bcabb46b8e63c6628b8":{
        "scriptId":"u44"},
      "2c088a37820542e4b6c54d17cb8a1f73":{
        "scriptId":"u45"},
      "22a2236b019f4c0d85f9bf6c9810663f":{
        "scriptId":"u46"},
      "025588abdc544956a1507208746c67b1":{
        "scriptId":"u47"},
      "929389a7a1e94f048aad52ebbc6b80b1":{
        "scriptId":"u48"},
      "6e83054ac4a3422f9a8907994a05b198":{
        "scriptId":"u49"},
      "b8a703289123470b9899232ca7ac5f8d":{
        "scriptId":"u50"},
      "e642186ef4914604b5f6a769fcf6e9dc":{
        "scriptId":"u51"},
      "3ed98a9773434025a315b824c2ebb580":{
        "scriptId":"u52"},
      "2748d776f31e4baf9358fbcad480b385":{
        "scriptId":"u53"},
      "1eb11f117f454f8d825850d53e8b5584":{
        "scriptId":"u54"},
      "377c4c27a8aa4618b186212187b48cd9":{
        "scriptId":"u55"},
      "3d541ed5db5d4f03bde40cca5c64cffa":{
        "scriptId":"u56"},
      "9222f31d50c2419e82ddef78ab2cf9ed":{
        "scriptId":"u57"},
      "8664c47e4af34fce8e1e2ffc339afe1c":{
        "scriptId":"u58"},
      "5c970c23b3ce49bca3430c587e0af62b":{
        "scriptId":"u59"},
      "404e561ae5a74471aebe7b8cd7315ab2":{
        "scriptId":"u60"},
      "33dd475d1b7c401fb4db8c79396f9572":{
        "scriptId":"u61"},
      "d4a61fee1913411a9213ab8bff0e50b2":{
        "scriptId":"u62"},
      "a75f8ffb1bdd498e80585c90dd9254d3":{
        "scriptId":"u63"},
      "52175b85fd3f4d72959d8d3115f5bdac":{
        "scriptId":"u64"}},
    "e138a44e8be7497986cd3504d506f7ce":{
      "scriptId":"u65"},
    "855162e9482a4c2d96d73d96bbb81445":{
      "scriptId":"u66"},
    "86eff52b62f848c38616516302249de8":{
      "scriptId":"u67"}}});