$axure.loadCurrentPage({
  "url":"鸡购买页.html",
  "generationDate":new Date(1458745318947.58),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"e10fe7513feb41fc8c464b171aad58d5",
    "type":"Axure:Page",
    "name":"鸡购买页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c860a1bcc16a4f78a36dde3ec64436e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":54},
            "size":{
              "width":104,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d24ff3b7acb4963aae801b22c13211e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":54},
                "size":{
                  "width":104,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u0.jpg"}},
{
          "id":"668b759bccec4b0f80e2f21881836d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":181},
            "size":{
              "width":33,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60665c04fd99461593e73726b6f33aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":181},
                "size":{
                  "width":33,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fd2a3ef1fc445558e5f31d5ed617dbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":233},
            "size":{
              "width":33,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98fe87f7bd744bf28c2c605358f2083a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":233},
                "size":{
                  "width":33,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a80c85f01d3147a2848171ca890201f5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":381},
            "size":{
              "width":838,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/鸡购买页/u6_line.png"}},
{
          "id":"6e7b5e8def2344ceaf841124a26a4b05",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":141},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e525c8dceb44d29c412c9bdec3c1c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":141},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a955894535e5456fb040dfba5d17cfbc",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":141},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e041c4a0f85f469eae51e97b88c2f921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":141},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"81be0dd44b184450af619c15eab265ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":180},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540ef5fb0074470096f270705a6cd997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":180},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"617e877e950442029132a09056ca42c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":233},
            "size":{
              "width":90,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"679147214e8b492799f6c1300df15fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":233},
                "size":{
                  "width":90,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u13.png"}},
{
          "id":"690555f4d778466e8a9809c96dd0b97e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":180},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f40e792c2bf48b9afe17adbe21d7140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":180},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"cba7f47dbc43417eb71e5fe633abcc3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":180},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aad6590ed6004cdd9680dcdbd7795105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":180},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"7e0132c9a8e343a9a25895405b8329db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":180},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c2c309cdfe4b08b03f26c9a66d2f03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":180},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"452ee25ed79d495395ad1bcc110d6735",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":233},
            "size":{
              "width":90,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbbd2bd57f0445ca89c252c9740e20d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":233},
                "size":{
                  "width":90,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u13.png"}},
{
          "id":"8200b76ed80e493682bc430606f58b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":232},
            "size":{
              "width":90,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6da437954854c90a483f076dd9af88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":232},
                "size":{
                  "width":90,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u13.png"}},
{
          "id":"b9e93a5a93b14155bfa82faa12438f9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":232},
            "size":{
              "width":90,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2c600fd3b5488abb8c66d586516249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":232},
                "size":{
                  "width":90,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u13.png"}},
{
          "id":"a7b71014b21b4869a2ffe8697887153c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":333},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"038e63b8be274fd3b491960c5e03a834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":333},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2470247aeebe4b5aa24200ac83fe21d9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":344},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"954b15efce014c5b9902c52d63a9ba57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":344},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"310b4dff917f4ea59366208408114da2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":344},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3904618aa0704a28a7a066209b77ba6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":517,
                  "y":344},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"61ee5971f8ea4ee0954403202addf6a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":481},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3098e232ae3b49e8bbf220157595d5b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":481},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u33.png"}},
{
          "id":"8e534ed1b5f245e3bcd0ae5c5d1dd29f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":231,
              "y":50},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118cdcddf6584d22b1cdef764afcf0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":50},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4c1ac98f0fb4007a81bd838be8115a5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":54},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f5507a46b938444ea855ae2e948b4860",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":135},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40f074db7cfc4842a7884566b93ea069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":135},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5902f0da78140188053dc677880d709",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":513},
            "size":{
              "width":161,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77bb329f9c44132b5857e33e35b8f69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":513},
                "size":{
                  "width":161,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b75c2d9da5214c8baefbf757ed0c759c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":286},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4906e1e2eae40e1a20d035f210e4413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":286},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d6c4e1ead041578ab3f692a770819a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":286},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c92c0825994226847843df0ded45b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":286},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"d880790f62af470695b2882b00dca4bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":286},
            "size":{
              "width":90,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1b3a2b2dc074ba78ddd3bb0e702699a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":286},
                "size":{
                  "width":90,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鸡购买页/u11.png"}},
{
          "id":"3d2d16adcc524b7aacfb8bcae5acc446",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":93},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6dbc50c6c0a44eaa41a00c911aa9674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":93},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d8a09710ea3486fb5ade91cda050e8c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":104},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7264663582e245a0bcc9e4b4e868397e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":104},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"257c7f115fab4faa8c6d3eaff66e374a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":104},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9de9b4e7efbd47afb1c3ee8865272e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":104},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffd2031c14f34e12b71b58411c4fb175",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":562,
              "y":104},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44be07ce6e444e35bedf10881a9acafd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":562,
                  "y":104},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ddb2c709937d4f40bfb0356fe7b502b1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"1134dc377d264422a0c693593837ca8f"}]}},
  "masters":{
    "1134dc377d264422a0c693593837ca8f":{
      "packageId":"1134dc377d264422a0c693593837ca8f",
      "type":"Axure:Master",
      "name":"宠物市场首页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"01db103b1d42496682389b8650ae1b37",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "location":{
                "x":50,
                "y":20},
              "size":{
                "width":498,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3cb5f59bebd249e8b4c9f4119dc416fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "location":{
                    "x":50,
                    "y":20},
                  "size":{
                    "width":498,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/鸡购买页/u57.png"}},
{
            "id":"bdafd491484041628f8584f1221fd3d9",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "location":{
                "x":78,
                "y":22},
              "size":{
                "width":81,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfaebb84a40545baa1720162931e69b9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "location":{
                    "x":78,
                    "y":22},
                  "size":{
                    "width":81,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的宠物",
                        "target":{
                          "targetType":"page",
                          "url":"我的宠物.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3248b4631375482dbb70b11035cf2cb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "location":{
                "x":220,
                "y":24},
              "size":{
                "width":81,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b478f32c45d0482c929424c6eaeeeee0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "location":{
                    "x":220,
                    "y":24},
                  "size":{
                    "width":81,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 宠物市场",
                        "target":{
                          "targetType":"page",
                          "url":"宠物市场.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c06598c721d64ceeb5e1d7f3ab367c54",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "location":{
                "x":369,
                "y":24},
              "size":{
                "width":61,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"835b30bf557741169ef7d240634b56ba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "location":{
                    "x":369,
                    "y":24},
                  "size":{
                    "width":61,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 屠宰场",
                        "target":{
                          "targetType":"page",
                          "url":"屠宰场.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "c860a1bcc16a4f78a36dde3ec64436e6":{
      "scriptId":"u0"},
    "5d24ff3b7acb4963aae801b22c13211e":{
      "scriptId":"u1"},
    "668b759bccec4b0f80e2f21881836d68":{
      "scriptId":"u2"},
    "60665c04fd99461593e73726b6f33aec":{
      "scriptId":"u3"},
    "1fd2a3ef1fc445558e5f31d5ed617dbd":{
      "scriptId":"u4"},
    "98fe87f7bd744bf28c2c605358f2083a":{
      "scriptId":"u5"},
    "a80c85f01d3147a2848171ca890201f5":{
      "scriptId":"u6"},
    "6e7b5e8def2344ceaf841124a26a4b05":{
      "scriptId":"u7"},
    "d0e525c8dceb44d29c412c9bdec3c1c7":{
      "scriptId":"u8"},
    "a955894535e5456fb040dfba5d17cfbc":{
      "scriptId":"u9"},
    "e041c4a0f85f469eae51e97b88c2f921":{
      "scriptId":"u10"},
    "81be0dd44b184450af619c15eab265ef":{
      "scriptId":"u11"},
    "540ef5fb0074470096f270705a6cd997":{
      "scriptId":"u12"},
    "617e877e950442029132a09056ca42c9":{
      "scriptId":"u13"},
    "679147214e8b492799f6c1300df15fe9":{
      "scriptId":"u14"},
    "690555f4d778466e8a9809c96dd0b97e":{
      "scriptId":"u15"},
    "4f40e792c2bf48b9afe17adbe21d7140":{
      "scriptId":"u16"},
    "cba7f47dbc43417eb71e5fe633abcc3b":{
      "scriptId":"u17"},
    "aad6590ed6004cdd9680dcdbd7795105":{
      "scriptId":"u18"},
    "7e0132c9a8e343a9a25895405b8329db":{
      "scriptId":"u19"},
    "21c2c309cdfe4b08b03f26c9a66d2f03":{
      "scriptId":"u20"},
    "452ee25ed79d495395ad1bcc110d6735":{
      "scriptId":"u21"},
    "bbbd2bd57f0445ca89c252c9740e20d7":{
      "scriptId":"u22"},
    "8200b76ed80e493682bc430606f58b04":{
      "scriptId":"u23"},
    "c6da437954854c90a483f076dd9af88d":{
      "scriptId":"u24"},
    "b9e93a5a93b14155bfa82faa12438f9d":{
      "scriptId":"u25"},
    "8a2c600fd3b5488abb8c66d586516249":{
      "scriptId":"u26"},
    "a7b71014b21b4869a2ffe8697887153c":{
      "scriptId":"u27"},
    "038e63b8be274fd3b491960c5e03a834":{
      "scriptId":"u28"},
    "2470247aeebe4b5aa24200ac83fe21d9":{
      "scriptId":"u29"},
    "954b15efce014c5b9902c52d63a9ba57":{
      "scriptId":"u30"},
    "310b4dff917f4ea59366208408114da2":{
      "scriptId":"u31"},
    "3904618aa0704a28a7a066209b77ba6d":{
      "scriptId":"u32"},
    "61ee5971f8ea4ee0954403202addf6a5":{
      "scriptId":"u33"},
    "3098e232ae3b49e8bbf220157595d5b7":{
      "scriptId":"u34"},
    "8e534ed1b5f245e3bcd0ae5c5d1dd29f":{
      "scriptId":"u35"},
    "118cdcddf6584d22b1cdef764afcf0ed":{
      "scriptId":"u36"},
    "b4c1ac98f0fb4007a81bd838be8115a5":{
      "scriptId":"u37"},
    "f5507a46b938444ea855ae2e948b4860":{
      "scriptId":"u38"},
    "40f074db7cfc4842a7884566b93ea069":{
      "scriptId":"u39"},
    "f5902f0da78140188053dc677880d709":{
      "scriptId":"u40"},
    "a77bb329f9c44132b5857e33e35b8f69":{
      "scriptId":"u41"},
    "b75c2d9da5214c8baefbf757ed0c759c":{
      "scriptId":"u42"},
    "c4906e1e2eae40e1a20d035f210e4413":{
      "scriptId":"u43"},
    "a0d6c4e1ead041578ab3f692a770819a":{
      "scriptId":"u44"},
    "79c92c0825994226847843df0ded45b6":{
      "scriptId":"u45"},
    "d880790f62af470695b2882b00dca4bc":{
      "scriptId":"u46"},
    "c1b3a2b2dc074ba78ddd3bb0e702699a":{
      "scriptId":"u47"},
    "3d2d16adcc524b7aacfb8bcae5acc446":{
      "scriptId":"u48"},
    "e6dbc50c6c0a44eaa41a00c911aa9674":{
      "scriptId":"u49"},
    "9d8a09710ea3486fb5ade91cda050e8c":{
      "scriptId":"u50"},
    "7264663582e245a0bcc9e4b4e868397e":{
      "scriptId":"u51"},
    "257c7f115fab4faa8c6d3eaff66e374a":{
      "scriptId":"u52"},
    "9de9b4e7efbd47afb1c3ee8865272e5f":{
      "scriptId":"u53"},
    "ffd2031c14f34e12b71b58411c4fb175":{
      "scriptId":"u54"},
    "44be07ce6e444e35bedf10881a9acafd":{
      "scriptId":"u55"},
    "ddb2c709937d4f40bfb0356fe7b502b1":{
      "scriptId":"u56",
      "01db103b1d42496682389b8650ae1b37":{
        "scriptId":"u57"},
      "3cb5f59bebd249e8b4c9f4119dc416fb":{
        "scriptId":"u58"},
      "bdafd491484041628f8584f1221fd3d9":{
        "scriptId":"u59"},
      "cfaebb84a40545baa1720162931e69b9":{
        "scriptId":"u60"},
      "3248b4631375482dbb70b11035cf2cb4":{
        "scriptId":"u61"},
      "b478f32c45d0482c929424c6eaeeeee0":{
        "scriptId":"u62"},
      "c06598c721d64ceeb5e1d7f3ab367c54":{
        "scriptId":"u63"},
      "835b30bf557741169ef7d240634b56ba":{
        "scriptId":"u64"}}}});