$axure.loadCurrentPage({
  "url":"我的收藏.html",
  "generationDate":new Date(1458745316618.53),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"6a78948d575a417daefde784ef607b3b",
    "type":"Axure:Page",
    "name":"我的收藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86af226cceec4133b5db17105f15e7c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":64},
            "size":{
              "width":114,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdaa79e1b5d64a9f99975c436bd93f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":64},
                "size":{
                  "width":114,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u0.png"}},
{
          "id":"efdef97d38c74394907ef1c48e3b3a6c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":120},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的收藏/u2_line.png"}},
{
          "id":"067c2a88c15f438aa063c89dc99cc8cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":170},
            "size":{
              "width":229,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a205dfe3401e4210946eba1bccaa3f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":170},
                "size":{
                  "width":229,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u3.png"}},
{
          "id":"d3c4eb540b2d4a9584be5606c9b19762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":343},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19c5b39e5fd5473594ca92c8ca855ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":343},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ea288831d344ba38883fd45a1542705",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":343},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6215189b54644dc99e0aab6081053d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":343},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfcedf92ebb044879036d415e845f6e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":170},
            "size":{
              "width":230,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2ebab2adac40a1a4b9983411d74597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":170},
                "size":{
                  "width":230,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u9.png"}},
{
          "id":"b77fc2221bb945de8038caed25830957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":343},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1dfe304aecc42538bc6afafe1201082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":343},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fc41fdbce044e01b5070f11c6e03941",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":343},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ed78161673a4489a0e5cf2c86663a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":343},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c502a7fba12e4c3291a7ba879860d4a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":170},
            "size":{
              "width":230,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312d51168de14c389f82e3b5f5aaadd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":170},
                "size":{
                  "width":230,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u15.png"}},
{
          "id":"c2fecbc0052b4f63ab7848be6db7fdc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":343},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb1db716bcae4a0bb742163aa6c4b5df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":343},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e01facc2c9144bc3bc95e47b5660c3a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":703,
              "y":343},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f810a7c823c432fb8af83e47929a00a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":703,
                  "y":343},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"160ce8fcf6204f869e9c52ad906155db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":140},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b98b478db154663b46209b35353de43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":140},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4423e5fd879f42758ffe8835e4014afb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":140},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5031a3317e34950a34122f783ae5499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":140},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b077b55ca7e45e983b3eb34e770c567",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":152},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的收藏/u2_line.png"}},
{
          "id":"f533d93f936d4325a6c41e94a6f22368",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4397116251964359abe28122c080b730"},
{
          "id":"4577368e2f104481b7c97b0b486f4053",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":10,
              "y":439},
            "size":{
              "width":1000,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69b7896a9a804e0ca927e2837c70f3fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":10,
                  "y":439},
                "size":{
                  "width":1000,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u115.png"}},
{
          "id":"8851b0e7555d4dd1ae188ebf1474f3a1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":414},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/购物车/u2_line.png"}}]}},
  "masters":{
    "4397116251964359abe28122c080b730":{
      "packageId":"4397116251964359abe28122c080b730",
      "type":"Axure:Master",
      "name":"我的交易导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d6bae1435ac64978b446d8da6c9890e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":64},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"575ecfba3c76482bba28b1c92b316e62",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":64},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"88e59cc71b87446382899684702a8e39",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":188},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13060b7507004e978062320e7975f9f5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":188},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"43e8339df3df494e899ca4a2f8eb000c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":228},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3efed88057734568a46b853096ec6677",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":228},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 评价管理",
                        "target":{
                          "targetType":"page",
                          "url":"评价管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"b6cb9ed2de9d4042ac9fea2a30e5f4df",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":104},
              "size":{
                "width":160,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b47d65e3530f45fd96e04c3212fee2c9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":104},
                  "size":{
                    "width":160,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的宝贝",
                        "target":{
                          "targetType":"page",
                          "url":"我的宝贝.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u39.png"}},
{
            "id":"151837040d954abe95564b6b2d75ff88",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":268},
              "size":{
                "width":160,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ee8aa69f240416ca26b231cfc7751cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":268},
                  "size":{
                    "width":160,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u41.png"}},
{
            "id":"143e85ac2680410493433cb7af8feac9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":304},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a28d91536924bcabb46b8e63c6628b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":304},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"2c088a37820542e4b6c54d17cb8a1f73",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":344},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"22a2236b019f4c0d85f9bf6c9810663f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":344},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"025588abdc544956a1507208746c67b1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":148},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"929389a7a1e94f048aad52ebbc6b80b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":148},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 收货地址",
                        "target":{
                          "targetType":"page",
                          "url":"收货地址.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/个人信息/u33.png"}},
{
            "id":"6e83054ac4a3422f9a8907994a05b198",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":20},
              "size":{
                "width":1000,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b8a703289123470b9899232ca7ac5f8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":20},
                  "size":{
                    "width":1000,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物车/u73.png"}},
{
            "id":"e642186ef4914604b5f6a769fcf6e9dc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":28},
              "size":{
                "width":105,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ed98a9773434025a315b824c2ebb580",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":28},
                  "size":{
                    "width":105,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2748d776f31e4baf9358fbcad480b385",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":28},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1eb11f117f454f8d825850d53e8b5584",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":28},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆",
                        "target":{
                          "targetType":"page",
                          "url":"登陆.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"377c4c27a8aa4618b186212187b48cd9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d541ed5db5d4f03bde40cca5c64cffa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 注册",
                        "target":{
                          "targetType":"page",
                          "url":"注册.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9222f31d50c2419e82ddef78ab2cf9ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":944,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8664c47e4af34fce8e1e2ffc339afe1c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":944,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c970c23b3ce49bca3430c587e0af62b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":887,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"404e561ae5a74471aebe7b8cd7315ab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":887,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"33dd475d1b7c401fb4db8c79396f9572",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":825,
                "y":27},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4a61fee1913411a9213ab8bff0e50b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":825,
                    "y":27},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的收藏",
                        "target":{
                          "targetType":"page",
                          "url":"我的收藏.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a75f8ffb1bdd498e80585c90dd9254d3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":757,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52175b85fd3f4d72959d8d3115f5bdac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":757,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "86af226cceec4133b5db17105f15e7c2":{
      "scriptId":"u0"},
    "fdaa79e1b5d64a9f99975c436bd93f1b":{
      "scriptId":"u1"},
    "efdef97d38c74394907ef1c48e3b3a6c":{
      "scriptId":"u2"},
    "067c2a88c15f438aa063c89dc99cc8cd":{
      "scriptId":"u3"},
    "a205dfe3401e4210946eba1bccaa3f6d":{
      "scriptId":"u4"},
    "d3c4eb540b2d4a9584be5606c9b19762":{
      "scriptId":"u5"},
    "19c5b39e5fd5473594ca92c8ca855ba3":{
      "scriptId":"u6"},
    "9ea288831d344ba38883fd45a1542705":{
      "scriptId":"u7"},
    "6215189b54644dc99e0aab6081053d88":{
      "scriptId":"u8"},
    "bfcedf92ebb044879036d415e845f6e6":{
      "scriptId":"u9"},
    "5c2ebab2adac40a1a4b9983411d74597":{
      "scriptId":"u10"},
    "b77fc2221bb945de8038caed25830957":{
      "scriptId":"u11"},
    "b1dfe304aecc42538bc6afafe1201082":{
      "scriptId":"u12"},
    "6fc41fdbce044e01b5070f11c6e03941":{
      "scriptId":"u13"},
    "4ed78161673a4489a0e5cf2c86663a5f":{
      "scriptId":"u14"},
    "c502a7fba12e4c3291a7ba879860d4a9":{
      "scriptId":"u15"},
    "312d51168de14c389f82e3b5f5aaadd0":{
      "scriptId":"u16"},
    "c2fecbc0052b4f63ab7848be6db7fdc1":{
      "scriptId":"u17"},
    "bb1db716bcae4a0bb742163aa6c4b5df":{
      "scriptId":"u18"},
    "e01facc2c9144bc3bc95e47b5660c3a8":{
      "scriptId":"u19"},
    "6f810a7c823c432fb8af83e47929a00a":{
      "scriptId":"u20"},
    "160ce8fcf6204f869e9c52ad906155db":{
      "scriptId":"u21"},
    "2b98b478db154663b46209b35353de43":{
      "scriptId":"u22"},
    "4423e5fd879f42758ffe8835e4014afb":{
      "scriptId":"u23"},
    "e5031a3317e34950a34122f783ae5499":{
      "scriptId":"u24"},
    "0b077b55ca7e45e983b3eb34e770c567":{
      "scriptId":"u25"},
    "f533d93f936d4325a6c41e94a6f22368":{
      "scriptId":"u26",
      "d6bae1435ac64978b446d8da6c9890e8":{
        "scriptId":"u27"},
      "575ecfba3c76482bba28b1c92b316e62":{
        "scriptId":"u28"},
      "88e59cc71b87446382899684702a8e39":{
        "scriptId":"u29"},
      "13060b7507004e978062320e7975f9f5":{
        "scriptId":"u30"},
      "43e8339df3df494e899ca4a2f8eb000c":{
        "scriptId":"u31"},
      "3efed88057734568a46b853096ec6677":{
        "scriptId":"u32"},
      "b6cb9ed2de9d4042ac9fea2a30e5f4df":{
        "scriptId":"u33"},
      "b47d65e3530f45fd96e04c3212fee2c9":{
        "scriptId":"u34"},
      "151837040d954abe95564b6b2d75ff88":{
        "scriptId":"u35"},
      "3ee8aa69f240416ca26b231cfc7751cf":{
        "scriptId":"u36"},
      "143e85ac2680410493433cb7af8feac9":{
        "scriptId":"u37"},
      "7a28d91536924bcabb46b8e63c6628b8":{
        "scriptId":"u38"},
      "2c088a37820542e4b6c54d17cb8a1f73":{
        "scriptId":"u39"},
      "22a2236b019f4c0d85f9bf6c9810663f":{
        "scriptId":"u40"},
      "025588abdc544956a1507208746c67b1":{
        "scriptId":"u41"},
      "929389a7a1e94f048aad52ebbc6b80b1":{
        "scriptId":"u42"},
      "6e83054ac4a3422f9a8907994a05b198":{
        "scriptId":"u43"},
      "b8a703289123470b9899232ca7ac5f8d":{
        "scriptId":"u44"},
      "e642186ef4914604b5f6a769fcf6e9dc":{
        "scriptId":"u45"},
      "3ed98a9773434025a315b824c2ebb580":{
        "scriptId":"u46"},
      "2748d776f31e4baf9358fbcad480b385":{
        "scriptId":"u47"},
      "1eb11f117f454f8d825850d53e8b5584":{
        "scriptId":"u48"},
      "377c4c27a8aa4618b186212187b48cd9":{
        "scriptId":"u49"},
      "3d541ed5db5d4f03bde40cca5c64cffa":{
        "scriptId":"u50"},
      "9222f31d50c2419e82ddef78ab2cf9ed":{
        "scriptId":"u51"},
      "8664c47e4af34fce8e1e2ffc339afe1c":{
        "scriptId":"u52"},
      "5c970c23b3ce49bca3430c587e0af62b":{
        "scriptId":"u53"},
      "404e561ae5a74471aebe7b8cd7315ab2":{
        "scriptId":"u54"},
      "33dd475d1b7c401fb4db8c79396f9572":{
        "scriptId":"u55"},
      "d4a61fee1913411a9213ab8bff0e50b2":{
        "scriptId":"u56"},
      "a75f8ffb1bdd498e80585c90dd9254d3":{
        "scriptId":"u57"},
      "52175b85fd3f4d72959d8d3115f5bdac":{
        "scriptId":"u58"}},
    "4577368e2f104481b7c97b0b486f4053":{
      "scriptId":"u59"},
    "69b7896a9a804e0ca927e2837c70f3fd":{
      "scriptId":"u60"},
    "8851b0e7555d4dd1ae188ebf1474f3a1":{
      "scriptId":"u61"}}});