$axure.loadCurrentPage({
  "url":"验证身份.html",
  "generationDate":new Date(1458745317667.32),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"b17049b318534e33915f58971c8b03cb",
    "type":"Axure:Page",
    "name":"验证身份",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11823bcd48434eb680f4a5e8e04bedf0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"c3119798c6134be7afe962f6f8b5da4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":950,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22a54acdb744e928ac5f18bcd6dbfaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":950,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u3.png"}},
{
          "id":"0fda945c2946462294af8ebaf7435180",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":150},
            "size":{
              "width":764,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"835d1cb684a84c369a43840167dfa08d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":150},
                "size":{
                  "width":764,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证身份/u5.png"}},
{
          "id":"387c0d17816246418b1e358ee8e0d1fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":260},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证身份/u7_line.png"}},
{
          "id":"4ebe4c68166e4d379bc5160be195e418",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":300},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a376fd4d2444a4b729bca7138be07e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":300},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30c32d3ec8454c13a89608b8f2326837",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":300},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2eff6ad59f645ee9617549bf39757fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":300},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eb5250bbbda240799cd2e8a18c4cfea7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":300},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6ecfafa03684c9290c956ee3ecfa91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":300},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c7959b775e464a528938a68e42b4051c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":337},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec20bf4184ec40a3b247fb2a23ede43c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":337},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cb6809e3f664dc3870a8b74241a79bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":370},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b48a0a4b8274bf49732c8e8a84f3953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":370},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e50325af4d246c4883bc29a852a74f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":370},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb0bfd9f93594cbd8c0e34509c38dec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":370},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ca0c3fdee4e46ab860c67975d6ec264",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":337},
            "size":{
              "width":103,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94eae6924ff04bbc8ec44a180073bf2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":337},
                "size":{
                  "width":103,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38e122db3dca4e519f1a2ec17d9d77c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":534},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa59e980e0c340b5a73047685a62f850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":534},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59b8765e0cff4e01afd088ee02aa2fae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":420},
            "size":{
              "width":135,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8f30593dc294464903cd6fed765b9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":420},
                "size":{
                  "width":135,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 找回密码",
                      "target":{
                        "targetType":"page",
                        "url":"找回密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/验证身份/u24.png"}},
{
          "id":"b821df7f2dbd45659fc21323a721080c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":420},
            "size":{
              "width":211,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e03a4b509e094a6883655c8823ecd2b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":471,
                  "y":420},
                "size":{
                  "width":211,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录邮箱",
                      "target":{
                        "targetType":"page",
                        "url":"登录邮箱.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/验证身份/u26.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "11823bcd48434eb680f4a5e8e04bedf0":{
      "scriptId":"u0",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u1"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u2"}},
    "c3119798c6134be7afe962f6f8b5da4b":{
      "scriptId":"u3"},
    "f22a54acdb744e928ac5f18bcd6dbfaf":{
      "scriptId":"u4"},
    "0fda945c2946462294af8ebaf7435180":{
      "scriptId":"u5"},
    "835d1cb684a84c369a43840167dfa08d":{
      "scriptId":"u6"},
    "387c0d17816246418b1e358ee8e0d1fe":{
      "scriptId":"u7"},
    "4ebe4c68166e4d379bc5160be195e418":{
      "scriptId":"u8"},
    "83a376fd4d2444a4b729bca7138be07e":{
      "scriptId":"u9"},
    "30c32d3ec8454c13a89608b8f2326837":{
      "scriptId":"u10"},
    "a2eff6ad59f645ee9617549bf39757fd":{
      "scriptId":"u11"},
    "eb5250bbbda240799cd2e8a18c4cfea7":{
      "scriptId":"u12"},
    "d6ecfafa03684c9290c956ee3ecfa91a":{
      "scriptId":"u13"},
    "c7959b775e464a528938a68e42b4051c":{
      "scriptId":"u14"},
    "ec20bf4184ec40a3b247fb2a23ede43c":{
      "scriptId":"u15"},
    "1cb6809e3f664dc3870a8b74241a79bb":{
      "scriptId":"u16"},
    "7b48a0a4b8274bf49732c8e8a84f3953":{
      "scriptId":"u17"},
    "6e50325af4d246c4883bc29a852a74f8":{
      "scriptId":"u18"},
    "fb0bfd9f93594cbd8c0e34509c38dec1":{
      "scriptId":"u19"},
    "2ca0c3fdee4e46ab860c67975d6ec264":{
      "scriptId":"u20"},
    "94eae6924ff04bbc8ec44a180073bf2f":{
      "scriptId":"u21"},
    "38e122db3dca4e519f1a2ec17d9d77c9":{
      "scriptId":"u22"},
    "fa59e980e0c340b5a73047685a62f850":{
      "scriptId":"u23"},
    "59b8765e0cff4e01afd088ee02aa2fae":{
      "scriptId":"u24"},
    "e8f30593dc294464903cd6fed765b9ef":{
      "scriptId":"u25"},
    "b821df7f2dbd45659fc21323a721080c":{
      "scriptId":"u26"},
    "e03a4b509e094a6883655c8823ecd2b8":{
      "scriptId":"u27"}}});