$axure.loadCurrentPage({
  "url":"设置密码.html",
  "generationDate":new Date(1458745317834.52),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"cb732da0fc9f4300a69f75847a94f1df",
    "type":"Axure:Page",
    "name":"设置密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41b8b22ba4634873abfa7de2741a2f6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"2b47675dae094b9584d9f97ff6ec94f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":950,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7669a6d12da6426cb02c849dff78e9f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":950,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u3.png"}},
{
          "id":"8192507c38bb4a4196b8c9e31ff083c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":150},
            "size":{
              "width":743,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfada335b9bb4e47938b827033d2f15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":150},
                "size":{
                  "width":743,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置密码/u5.png"}},
{
          "id":"ec616981af254ef39e8f6e8cf9545f1f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":260},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证身份/u7_line.png"}},
{
          "id":"9d9b39e01b034d0580dd9823d91a4b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":534},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9eaf67ad6c4ffc9c10d39bfa90e345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":534},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7ccc804d2744602b580dcc29b2b90a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":327,
              "y":308},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94d8715f9c49458ca8b4549195a3c9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":327,
                  "y":308},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcfb1350f28348d28fa69a6fe3bdc353",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":295,
              "y":361},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed9747a61104f6a9cbd24552c2aa784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":295,
                  "y":361},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6099f477a883427fb260a8ee6ca11bc3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":294},
            "size":{
              "width":300,
              "height":37}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入新登录密码"},
{
          "id":"d0100f4f4c384d4196e0801f4d7fe72d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":354},
            "size":{
              "width":300,
              "height":37}},
          "adaptiveStyles":{
},
          "placeholderText":"请再次输入新登录密码"},
{
          "id":"803a6038c39447d9b8237fc0ddf00c10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":416},
            "size":{
              "width":136,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288268c9279a4cd38f871cd3e7d6d31c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":416},
                "size":{
                  "width":136,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 完成",
                      "target":{
                        "targetType":"page",
                        "url":"完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置密码/u16.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "41b8b22ba4634873abfa7de2741a2f6e":{
      "scriptId":"u0",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u1"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u2"}},
    "2b47675dae094b9584d9f97ff6ec94f8":{
      "scriptId":"u3"},
    "7669a6d12da6426cb02c849dff78e9f2":{
      "scriptId":"u4"},
    "8192507c38bb4a4196b8c9e31ff083c4":{
      "scriptId":"u5"},
    "cfada335b9bb4e47938b827033d2f15d":{
      "scriptId":"u6"},
    "ec616981af254ef39e8f6e8cf9545f1f":{
      "scriptId":"u7"},
    "9d9b39e01b034d0580dd9823d91a4b40":{
      "scriptId":"u8"},
    "5d9eaf67ad6c4ffc9c10d39bfa90e345":{
      "scriptId":"u9"},
    "c7ccc804d2744602b580dcc29b2b90a0":{
      "scriptId":"u10"},
    "94d8715f9c49458ca8b4549195a3c9ad":{
      "scriptId":"u11"},
    "bcfb1350f28348d28fa69a6fe3bdc353":{
      "scriptId":"u12"},
    "2ed9747a61104f6a9cbd24552c2aa784":{
      "scriptId":"u13"},
    "6099f477a883427fb260a8ee6ca11bc3":{
      "scriptId":"u14"},
    "d0100f4f4c384d4196e0801f4d7fe72d":{
      "scriptId":"u15"},
    "803a6038c39447d9b8237fc0ddf00c10":{
      "scriptId":"u16"},
    "288268c9279a4cd38f871cd3e7d6d31c":{
      "scriptId":"u17"}}});