$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1458745318088.31),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"86337b7d65f448ada87075438c8f07e1",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF00BE9C},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bddd96c9c9ed4d80a4b67fbefb97312e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":140},
            "size":{
              "width":350,
              "height":390}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd3ab62ef4fe4f1a85f27b88ce337b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":140},
                "size":{
                  "width":350,
                  "height":390}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"307c61e67e4e457abe2c4c0cd5525b52",
          "label":"name",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":223},
            "size":{
              "width":260,
              "height":41}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号/会员名/邮箱"},
{
          "id":"d13b46a776eb4cdabc625f36979eac94",
          "label":"pass",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":279},
            "size":{
              "width":260,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入密码"},
{
          "id":"9bb517aace7b49088e48669d8d155550",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":200,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a059f730e004631b0052b4c06cf780a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":200,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u1.png"}},
{
          "id":"dc52684081b3445eb3c836548059e322",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":223},
            "size":{
              "width":39,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ef1fbc3f76445cb57bca34f1111e2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":223},
                "size":{
                  "width":39,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"2e4b8be152214ceab2059f38fa928030",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":279},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9363cd5234d64d52a2b3cea645c4c6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":279},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u8.png"}},
{
          "id":"3026020c95704380b12b73afa8ac7108",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":630,
              "y":165},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b3a774908d4c898eccf7b7cb8b1620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":630,
                  "y":165},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9b00e3b2d1646c8a189026573a99a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":344},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a3ba952d0240fcae2b70f4595afcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":344},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28ff31fd31ca42a19f477307cef486a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":387},
            "size":{
              "width":300,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a35008be8c1464a86754397a58f4a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":387},
                "size":{
                  "width":300,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 name = &quot;手机号/会员名/邮箱&quot; 和 文字于 pass = &quot;请输入密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["307c61e67e4e457abe2c4c0cd5525b52"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"手机号/会员名/邮箱",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["d13b46a776eb4cdabc625f36979eac94"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"请输入密码",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 statusLabel = &quot;请输入用户名密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["00a02bec19564006bf056f0effbdd794"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入用户名密码",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setPanelState",
                      "description":"设置 ST to 状态1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["355848195e1045e6a1618c3707c309bc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If 文字于 name = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["307c61e67e4e457abe2c4c0cd5525b52"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 staus to 状态1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["4d0f8dbc881342e3a67272e3130a374c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;请输入用户名&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["36145a9af30a40adbe652d483d6ad467"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入用户名",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"用例 3<br> (Else If 文字于 pass = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["d13b46a776eb4cdabc625f36979eac94"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 staus to 状态1 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["4d0f8dbc881342e3a67272e3130a374c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;请输入密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["36145a9af30a40adbe652d483d6ad467"]},
{
                                "exprType":"stringLiteral",
                                "value":"请输入密码",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"用例 4<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 ST to 状态1",
                      "panelsToStates":[{
                          "panelPath":["355848195e1045e6a1618c3707c309bc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"setFunction",
                      "description":"设置 文字于 statusLabel = &quot;登录成功&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["00a02bec19564006bf056f0effbdd794"]},
{
                                "exprType":"stringLiteral",
                                "value":"登录成功",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u14.png"}},
{
          "id":"355848195e1045e6a1618c3707c309bc",
          "label":"ST",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":630,
              "y":194},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"cbab6764b5f244deb2efea8d2d98612b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fcb7306372024908bf988af6842191ed",
                  "label":"statusPanl",
                  "parentDynamicPanel":"355848195e1045e6a1618c3707c309bc",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"317ed40d86634264be6d481c81b2a07d",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"4d0f8dbc881342e3a67272e3130a374c",
                          "label":"staus",
                          "parentDynamicPanel":"fcb7306372024908bf988af6842191ed",
                          "type":"dynamicPanel",
                          "styleType":"dynamicPanel",
                          "visible":false,
                          "style":{
                            "size":{
                              "width":10,
                              "height":10},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "scrollbars":"none",
                          "fitToContent":true,
                          "propagate":false,
                          "diagrams":[{
                              "id":"1be31ba75abf48819b2818deabfd6396",
                              "label":"状态1",
                              "type":"Axure:PanelDiagram",
                              "objects":[{
                                  "id":"93b619dfc2f648f69047a23a5f9814ef",
                                  "label":"",
                                  "parentDynamicPanel":"4d0f8dbc881342e3a67272e3130a374c",
                                  "type":"buttonShape",
                                  "styleType":"buttonShape",
                                  "visible":true,
                                  "style":{
                                    "size":{
                                      "width":200,
                                      "height":23}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"36145a9af30a40adbe652d483d6ad467",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"4d0f8dbc881342e3a67272e3130a374c",
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "size":{
                                          "width":200,
                                          "height":23}},
                                      "adaptiveStyles":{
}}],
                                  "images":{
                                    "normal~":"images/登陆/u19.png"}}],
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "image":null,
                                "imageHorizontalAlignment":"near",
                                "imageVerticalAlignment":"near",
                                "imageRepeat":"auto"},
                              "adaptiveStyles":{
}}]},
{
                          "id":"07d84e82308a4e19b5e44a380c561216",
                          "label":"",
                          "parentDynamicPanel":"fcb7306372024908bf988af6842191ed",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":22,
                              "height":23}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6e2b57b9771c43229955f515760eca52",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"fcb7306372024908bf988af6842191ed",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":22,
                                  "height":23}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/登陆/u21.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xDDDDDD},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"eb9082b140b54223bafa79bedfa2d336",
                  "label":"statusLabel",
                  "parentDynamicPanel":"355848195e1045e6a1618c3707c309bc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":23,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00a02bec19564006bf056f0effbdd794",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"355848195e1045e6a1618c3707c309bc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "location":{
                          "x":23,
                          "y":0},
                        "size":{
                          "width":178,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"bd880d6d1a04442192d0ed34f02fe123",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"1c61bde8545e428682d238b7c46ccd33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":22,
              "y":570},
            "size":{
              "width":1000,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78c3fe0b47e49d498b694e00b86869e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":22,
                  "y":570},
                "size":{
                  "width":1000,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u28.png"}},
{
          "id":"367e3bd20e714c8b9e1caed450e15943",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":140},
            "size":{
              "width":526,
              "height":390}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558164ccbd8f4c4f90d5de9966d56b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":140},
                "size":{
                  "width":526,
                  "height":390}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u30.jpg"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "bddd96c9c9ed4d80a4b67fbefb97312e":{
      "scriptId":"u0"},
    "dd3ab62ef4fe4f1a85f27b88ce337b01":{
      "scriptId":"u1"},
    "307c61e67e4e457abe2c4c0cd5525b52":{
      "scriptId":"u2"},
    "d13b46a776eb4cdabc625f36979eac94":{
      "scriptId":"u3"},
    "9bb517aace7b49088e48669d8d155550":{
      "scriptId":"u4"},
    "4a059f730e004631b0052b4c06cf780a":{
      "scriptId":"u5"},
    "dc52684081b3445eb3c836548059e322":{
      "scriptId":"u6"},
    "90ef1fbc3f76445cb57bca34f1111e2e":{
      "scriptId":"u7"},
    "2e4b8be152214ceab2059f38fa928030":{
      "scriptId":"u8"},
    "9363cd5234d64d52a2b3cea645c4c6e5":{
      "scriptId":"u9"},
    "3026020c95704380b12b73afa8ac7108":{
      "scriptId":"u10"},
    "48b3a774908d4c898eccf7b7cb8b1620":{
      "scriptId":"u11"},
    "b9b00e3b2d1646c8a189026573a99a4b":{
      "scriptId":"u12"},
    "d7a3ba952d0240fcae2b70f4595afcca":{
      "scriptId":"u13"},
    "28ff31fd31ca42a19f477307cef486a9":{
      "scriptId":"u14"},
    "6a35008be8c1464a86754397a58f4a42":{
      "scriptId":"u15"},
    "355848195e1045e6a1618c3707c309bc":{
      "scriptId":"u16"},
    "fcb7306372024908bf988af6842191ed":{
      "scriptId":"u17"},
    "4d0f8dbc881342e3a67272e3130a374c":{
      "scriptId":"u18"},
    "93b619dfc2f648f69047a23a5f9814ef":{
      "scriptId":"u19"},
    "36145a9af30a40adbe652d483d6ad467":{
      "scriptId":"u20"},
    "07d84e82308a4e19b5e44a380c561216":{
      "scriptId":"u21"},
    "6e2b57b9771c43229955f515760eca52":{
      "scriptId":"u22"},
    "eb9082b140b54223bafa79bedfa2d336":{
      "scriptId":"u23"},
    "00a02bec19564006bf056f0effbdd794":{
      "scriptId":"u24"},
    "bd880d6d1a04442192d0ed34f02fe123":{
      "scriptId":"u25",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u26"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u27"}},
    "1c61bde8545e428682d238b7c46ccd33":{
      "scriptId":"u28"},
    "a78c3fe0b47e49d498b694e00b86869e":{
      "scriptId":"u29"},
    "367e3bd20e714c8b9e1caed450e15943":{
      "scriptId":"u30"},
    "558164ccbd8f4c4f90d5de9966d56b54":{
      "scriptId":"u31"}}});