$axure.loadCurrentPage({
  "url":"完成.html",
  "generationDate":new Date(1458745317906.13),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"94804436d0c54c9b953b4e3ef6bcfc62",
    "type":"Axure:Page",
    "name":"完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2abe6285bc144771a30229abccb83246",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"68ada3e869e14b92af91999b5ee615f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":950,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c23808e794ab436f82a2ad66e44e3771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":950,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u3.png"}},
{
          "id":"61f1432a778d4fb68488f62ef4c9fdf9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":150},
            "size":{
              "width":711,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3523bf213c1402b808583179f9d9dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":150},
                "size":{
                  "width":711,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/完成/u5.png"}},
{
          "id":"fc21c3f5374f461f9a3f396285545ae1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":260},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证身份/u7_line.png"}},
{
          "id":"f25b6ecb94154302a7aa8f33cac931f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":534},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5385c32cddbc43488476cc0c12baf180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":534},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0549bbcca8f44acebc290654dfd58225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":407,
              "y":314},
            "size":{
              "width":311,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"624888cefb0c4bb9b9e85b5d303988e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":407,
                  "y":314},
                "size":{
                  "width":311,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c46165362c4dd0bc243f994ab10659",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":314},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d08ac147504ce994da9f626fe5ef53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":314},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/完成/u12.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "2abe6285bc144771a30229abccb83246":{
      "scriptId":"u0",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u1"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u2"}},
    "68ada3e869e14b92af91999b5ee615f8":{
      "scriptId":"u3"},
    "c23808e794ab436f82a2ad66e44e3771":{
      "scriptId":"u4"},
    "61f1432a778d4fb68488f62ef4c9fdf9":{
      "scriptId":"u5"},
    "b3523bf213c1402b808583179f9d9dc6":{
      "scriptId":"u6"},
    "fc21c3f5374f461f9a3f396285545ae1":{
      "scriptId":"u7"},
    "f25b6ecb94154302a7aa8f33cac931f7":{
      "scriptId":"u8"},
    "5385c32cddbc43488476cc0c12baf180":{
      "scriptId":"u9"},
    "0549bbcca8f44acebc290654dfd58225":{
      "scriptId":"u10"},
    "624888cefb0c4bb9b9e85b5d303988e9":{
      "scriptId":"u11"},
    "e1c46165362c4dd0bc243f994ab10659":{
      "scriptId":"u12"},
    "c4d08ac147504ce994da9f626fe5ef53":{
      "scriptId":"u13"}}});