$axure.loadCurrentPage({
  "url":"登录邮箱.html",
  "generationDate":new Date(1458745317773.44),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"f9f1f3833c7b431b902999f109e5ebae",
    "type":"Axure:Page",
    "name":"登录邮箱",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b56a303d22654198b4907855061abfc9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2"},
{
          "id":"6327810c8aa54348870c0e97e0e448e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":120},
            "size":{
              "width":950,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1beb6c7ce5c942ab8e9655607fc8d355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":120},
                "size":{
                  "width":950,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找回密码/u3.png"}},
{
          "id":"3aada37ea51d4c4c9154061efcc78804",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":150},
            "size":{
              "width":764,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b4a9797dce4862901e29e05233c1b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":150},
                "size":{
                  "width":764,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/验证身份/u5.png"}},
{
          "id":"a9276252b95a4235a2e0e0ffcdd59463",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":260},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证身份/u7_line.png"}},
{
          "id":"9bb2c81997ec45b0b0b94f0c1c1ce481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":300},
            "size":{
              "width":424,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8a8a4a5a32046f7a2479b786a2de414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":300},
                "size":{
                  "width":424,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de85985f7d7c40f19c59974c69bc12c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":534},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a6e778758445bebfc9d75091f0ea67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":534},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5f28b145f954f76b8a80df98c41a221",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":382},
            "size":{
              "width":421,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0373c8538f41c5b0594918bf928f50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":321,
                  "y":382},
                "size":{
                  "width":421,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84dd9767d46f40759edb564adf1c0702",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":328},
            "size":{
              "width":180,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0466ec00134b449dede04c70d561e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":328},
                "size":{
                  "width":180,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置密码",
                      "target":{
                        "targetType":"page",
                        "url":"设置密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录邮箱/u14.png"}}]}},
  "masters":{
    "65f1fa3bb32e43aa8a1ca3bbd21b26e2":{
      "packageId":"65f1fa3bb32e43aa8a1ca3bbd21b26e2",
      "type":"Axure:Master",
      "name":"logo",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d54f4d5e13ff4728b457404b244230e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":30,
                "y":20},
              "size":{
                "width":200,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e8988d957a6942c094242a413ec707a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":30,
                    "y":20},
                  "size":{
                    "width":200,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/找回密码/u1.png"}}]}}},
  "objectPaths":{
    "b56a303d22654198b4907855061abfc9":{
      "scriptId":"u0",
      "d54f4d5e13ff4728b457404b244230e8":{
        "scriptId":"u1"},
      "e8988d957a6942c094242a413ec707a9":{
        "scriptId":"u2"}},
    "6327810c8aa54348870c0e97e0e448e8":{
      "scriptId":"u3"},
    "1beb6c7ce5c942ab8e9655607fc8d355":{
      "scriptId":"u4"},
    "3aada37ea51d4c4c9154061efcc78804":{
      "scriptId":"u5"},
    "93b4a9797dce4862901e29e05233c1b2":{
      "scriptId":"u6"},
    "a9276252b95a4235a2e0e0ffcdd59463":{
      "scriptId":"u7"},
    "9bb2c81997ec45b0b0b94f0c1c1ce481":{
      "scriptId":"u8"},
    "d8a8a4a5a32046f7a2479b786a2de414":{
      "scriptId":"u9"},
    "de85985f7d7c40f19c59974c69bc12c6":{
      "scriptId":"u10"},
    "59a6e778758445bebfc9d75091f0ea67":{
      "scriptId":"u11"},
    "c5f28b145f954f76b8a80df98c41a221":{
      "scriptId":"u12"},
    "cc0373c8538f41c5b0594918bf928f50":{
      "scriptId":"u13"},
    "84dd9767d46f40759edb564adf1c0702":{
      "scriptId":"u14"},
    "5f0466ec00134b449dede04c70d561e6":{
      "scriptId":"u15"}}});