package com.jiuji.cn.model;
 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TClass generated by hbm2java
 */
@Entity
@Table(name = "t_class", catalog = "shop")
public class TClass implements java.io.Serializable {

	private Integer FClsId;
	private String FClsName;
	private Integer FStatus;
	private Integer FOrder;
	private Integer FPClsId;
	
	//子类列表
	private Set<TClass> sonTClasses = new HashSet<TClass>();
	//产品列表
	private Set<TProduct> TProducts = new HashSet<TProduct>();

	public TClass() {
	}

	public TClass(String FClsName, Integer FStatus, Integer FOrder, Integer FPClsId, Set<TProduct> TProducts) {
		this.FClsName = FClsName;
		this.FStatus = FStatus;
		this.FOrder = FOrder;
		this.FPClsId = FPClsId;
		this.TProducts = TProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "F_ClsId", unique = true, nullable = false)
	public Integer getFClsId() {
		return this.FClsId;
	}

	public void setFClsId(Integer FClsId) {
		this.FClsId = FClsId;
	}

	@Column(name = "F_ClsName", length = 44)
	public String getFClsName() {
		return this.FClsName;
	}

	public void setFClsName(String FClsName) {
		this.FClsName = FClsName;
	}

	@Column(name = "F_Status")
	public Integer getFStatus() {
		return this.FStatus;
	}

	public void setFStatus(Integer FStatus) {
		this.FStatus = FStatus;
	}

	@Column(name = "F_Order")
	public Integer getFOrder() {
		return this.FOrder;
	}

	public void setFOrder(Integer FOrder) {
		this.FOrder = FOrder;
	}
 
	public Integer getFPClsId() {
		return FPClsId;
	}

	public void setFPClsId(Integer fPClsId) {
		FPClsId = fPClsId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TClass")
	public Set<TProduct> getTProducts() {
		return this.TProducts;
	}

	public void setTProducts(Set<TProduct> TProducts) {
		this.TProducts = TProducts;
	}

	public Set<TClass> getSonTClasses() {
		return sonTClasses;
	}

	public void setSonTClasses(Set<TClass> sonTClasses) {
		this.sonTClasses = sonTClasses;
	}

}
