package com.jiuji.cn.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "t_order", catalog = "shop")
public class TOrder implements java.io.Serializable {

	private String FOrderId;
	private String FUserId;
	private String FProduceId;
	private BigDecimal FSinglePrice;
	private Integer FBuyCount;
	private Long FCost;
	private String FMessage;
	private Integer FStatus;

	public TOrder() {
	}

	public TOrder(String FOrderId) {
		this.FOrderId = FOrderId;
	}

	public TOrder(String FOrderId, String FUserId, String FProduceId, BigDecimal FSinglePrice, Integer FBuyCount,
			Long FCost, String FMessage, Integer FStatus) {
		this.FOrderId = FOrderId;
		this.FUserId = FUserId;
		this.FProduceId = FProduceId;
		this.FSinglePrice = FSinglePrice;
		this.FBuyCount = FBuyCount;
		this.FCost = FCost;
		this.FMessage = FMessage;
		this.FStatus = FStatus;
	}

	@Id

	@Column(name = "F_OrderId", unique = true, nullable = false, length = 44)
	public String getFOrderId() {
		return this.FOrderId;
	}

	public void setFOrderId(String FOrderId) {
		this.FOrderId = FOrderId;
	}

	@Column(name = "F_UserId", length = 44)
	public String getFUserId() {
		return this.FUserId;
	}

	public void setFUserId(String FUserId) {
		this.FUserId = FUserId;
	}

	@Column(name = "F_ProduceId", length = 44)
	public String getFProduceId() {
		return this.FProduceId;
	}

	public void setFProduceId(String FProduceId) {
		this.FProduceId = FProduceId;
	}

	@Column(name = "F_SinglePrice", precision = 44, scale = 0)
	public BigDecimal getFSinglePrice() {
		return this.FSinglePrice;
	}

	public void setFSinglePrice(BigDecimal FSinglePrice) {
		this.FSinglePrice = FSinglePrice;
	}

	@Column(name = "F_BuyCount")
	public Integer getFBuyCount() {
		return this.FBuyCount;
	}

	public void setFBuyCount(Integer FBuyCount) {
		this.FBuyCount = FBuyCount;
	}

	@Column(name = "F_Cost", precision = 11, scale = 0)
	public Long getFCost() {
		return this.FCost;
	}

	public void setFCost(Long FCost) {
		this.FCost = FCost;
	}

	@Column(name = "F_Message", length = 65535)
	public String getFMessage() {
		return this.FMessage;
	}

	public void setFMessage(String FMessage) {
		this.FMessage = FMessage;
	}

	@Column(name = "F_Status")
	public Integer getFStatus() {
		return this.FStatus;
	}

	public void setFStatus(Integer FStatus) {
		this.FStatus = FStatus;
	}

}
