package com.jiuji.cn.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSousou generated by hbm2java
 */
@Entity
@Table(name = "t_sousou", catalog = "shop")
public class TSousou implements java.io.Serializable {

	private String userId;
	private String keyword;

	public TSousou() {
	}

	public TSousou(String userId) {
		this.userId = userId;
	}

	public TSousou(String userId, String keyword) {
		this.userId = userId;
		this.keyword = keyword;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false, length = 11)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "keyword", length = 44)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
