$axure.loadCurrentPage({
  "url":"累计评论.html",
  "generationDate":new Date(1458745317188.88),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"eed9df0a7614424a840566069eeaae3c",
    "type":"Axure:Page",
    "name":"累计评论",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1743761fc958498e989cc474083a96ca",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":12},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4068c4e3208b43e9a9d044373c104392",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b648abb53ac4f90a27bdef03b56aca4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40b5d05a5b774eb9955b630efe091948",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/累计评论/u2.png"}},
{
                  "id":"3d619af47fcf479f944105541afbc7cb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85fe16e80afe4058b20d962c05f7cb45",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/累计评论/u4.png"}}]}]},
{
          "id":"301394523a074d0db807bf450265c359",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":32,
              "y":42},
            "size":{
              "width":770,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a7698df179457fab7328c7d7558e43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":32,
                  "y":42},
                "size":{
                  "width":770,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u6.png"}},
{
          "id":"04b8ca40ed574edb8ccf0bd710558ffa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":52},
            "size":{
              "width":31,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34077d37cee47c7ba70e69ab9b84b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":52},
                "size":{
                  "width":31,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u8.png"}},
{
          "id":"574ac2291e5044c08332ab29e08ae958",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":52},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60fec1fc6ad64b658fb5ed3b81b9d62e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":52},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb43921bd944de19af59c66d371bcf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":32,
              "y":100},
            "size":{
              "width":770,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6744a57eaf84f67a86eb5653d97724e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":32,
                  "y":100},
                "size":{
                  "width":770,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u6.png"}},
{
          "id":"d60a6ae6e0184e0eb209dc4a37eeabdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":32,
              "y":158},
            "size":{
              "width":770,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abc5bb0eff04ec383f71f0e0f46bf70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":32,
                  "y":158},
                "size":{
                  "width":770,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u6.png"}},
{
          "id":"213a0bae26c848de9943965bda84e04a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":110},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5afef33d7ac946e99d81bb7da4d72999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":110},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u16.png"}},
{
          "id":"dd0eac79a96b4df3abc3033c1cafbee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":110},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d15555cd38c47faa8700fb541882e44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":110},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6001adb4b4f4ae7a846d294c6df8377",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":166},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64cf5625d6b644f0bcda63fd02956046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":166},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u20.png"}},
{
          "id":"dd714ade67af43d68a3d47a327e4ff53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":166},
            "size":{
              "width":105,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edfbbc9cdfa04ac3a6c0ddcb64158c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":166},
                "size":{
                  "width":105,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16310096d0b14f9bb541dccc78287281",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":32,
              "y":216},
            "size":{
              "width":770,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7680f62b20054eecb132988cbd8aff4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":32,
                  "y":216},
                "size":{
                  "width":770,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u6.png"}},
{
          "id":"a167b80fbd2948ef82cc4953d40163a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":226},
            "size":{
              "width":29,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16d08d4f008a4e3aa635c01ecf7f64b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":226},
                "size":{
                  "width":29,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/累计评论/u26.png"}},
{
          "id":"f11a858258724530a947724476ddf342",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":226},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cae938b6a134df9ad48f136f76ab658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":226},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb0e547041844d7baf9bd5d254c294ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":63},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d9bad9de134c4b820187dcdbc61ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":63},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9850b9e3ad52453eabfbba69d2231f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":121},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee2324603fd425abba59ed6b2a832de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":121},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d2879c26acb4187b72e1ef4fe7e3269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":175},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d019951db54c4d2cb6ea1663cfae7cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":175},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"773a8fb04006441199fde66cc99400cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":234},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408176ec928a475d94b12132d9032cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":234},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1743761fc958498e989cc474083a96ca":{
      "scriptId":"u0"},
    "4068c4e3208b43e9a9d044373c104392":{
      "scriptId":"u1"},
    "5b648abb53ac4f90a27bdef03b56aca4":{
      "scriptId":"u2"},
    "40b5d05a5b774eb9955b630efe091948":{
      "scriptId":"u3"},
    "3d619af47fcf479f944105541afbc7cb":{
      "scriptId":"u4"},
    "85fe16e80afe4058b20d962c05f7cb45":{
      "scriptId":"u5"},
    "301394523a074d0db807bf450265c359":{
      "scriptId":"u6"},
    "22a7698df179457fab7328c7d7558e43":{
      "scriptId":"u7"},
    "04b8ca40ed574edb8ccf0bd710558ffa":{
      "scriptId":"u8"},
    "c34077d37cee47c7ba70e69ab9b84b76":{
      "scriptId":"u9"},
    "574ac2291e5044c08332ab29e08ae958":{
      "scriptId":"u10"},
    "60fec1fc6ad64b658fb5ed3b81b9d62e":{
      "scriptId":"u11"},
    "5eb43921bd944de19af59c66d371bcf9":{
      "scriptId":"u12"},
    "e6744a57eaf84f67a86eb5653d97724e":{
      "scriptId":"u13"},
    "d60a6ae6e0184e0eb209dc4a37eeabdb":{
      "scriptId":"u14"},
    "7abc5bb0eff04ec383f71f0e0f46bf70":{
      "scriptId":"u15"},
    "213a0bae26c848de9943965bda84e04a":{
      "scriptId":"u16"},
    "5afef33d7ac946e99d81bb7da4d72999":{
      "scriptId":"u17"},
    "dd0eac79a96b4df3abc3033c1cafbee6":{
      "scriptId":"u18"},
    "3d15555cd38c47faa8700fb541882e44":{
      "scriptId":"u19"},
    "d6001adb4b4f4ae7a846d294c6df8377":{
      "scriptId":"u20"},
    "64cf5625d6b644f0bcda63fd02956046":{
      "scriptId":"u21"},
    "dd714ade67af43d68a3d47a327e4ff53":{
      "scriptId":"u22"},
    "edfbbc9cdfa04ac3a6c0ddcb64158c36":{
      "scriptId":"u23"},
    "16310096d0b14f9bb541dccc78287281":{
      "scriptId":"u24"},
    "7680f62b20054eecb132988cbd8aff4f":{
      "scriptId":"u25"},
    "a167b80fbd2948ef82cc4953d40163a2":{
      "scriptId":"u26"},
    "16d08d4f008a4e3aa635c01ecf7f64b3":{
      "scriptId":"u27"},
    "f11a858258724530a947724476ddf342":{
      "scriptId":"u28"},
    "8cae938b6a134df9ad48f136f76ab658":{
      "scriptId":"u29"},
    "bb0e547041844d7baf9bd5d254c294ec":{
      "scriptId":"u30"},
    "23d9bad9de134c4b820187dcdbc61ab6":{
      "scriptId":"u31"},
    "9850b9e3ad52453eabfbba69d2231f18":{
      "scriptId":"u32"},
    "8ee2324603fd425abba59ed6b2a832de":{
      "scriptId":"u33"},
    "6d2879c26acb4187b72e1ef4fe7e3269":{
      "scriptId":"u34"},
    "d019951db54c4d2cb6ea1663cfae7cee":{
      "scriptId":"u35"},
    "773a8fb04006441199fde66cc99400cc":{
      "scriptId":"u36"},
    "408176ec928a475d94b12132d9032cd4":{
      "scriptId":"u37"}}});