$axure.loadCurrentPage({
  "url":"订单确定页.html",
  "generationDate":new Date(1458745318816.41),
  "isCanvasEnabled":false,
  "variables":["content",
"NewVariable"],
  "page":{
    "packageId":"e046abb1b8894a9e9cc9c6d0eefe04ce",
    "type":"Axure:Page",
    "name":"订单确定页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa3b8d00517248ebb55d3e4b373b41cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"752678b54ff64da98ec86d22b68d7334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b49ae2ca607b42f98c38dc649ccfd2d4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":27},
            "size":{
              "width":970,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单确定页/u2_line.png"}},
{
          "id":"ba1a014f99a940e9830a98ffc335aad4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":43},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a587617e31b5462b808d13f0694af34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":43},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"877ec16fe76b47d69374ad832777ea2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":43},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab734cfebfa645f2891978d3ba438878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":43},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c2182ca2e1d4d45834550e547de9547",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":473,
              "y":43},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb63809f863455a9cb375389ff750a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":473,
                  "y":43},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c10d45c5d34982b309c8a52c87ce35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":43},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd16ab31c534bbba7d10b46557b0a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":654,
                  "y":43},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c628371939974c9f989b0e6806fe1281",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":73},
            "size":{
              "width":970,
              "height":136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac641e667b947cba37957c48fc2f8c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":73},
                "size":{
                  "width":970,
                  "height":136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确定页/u11.png"}},
{
          "id":"56c68c2e4c1e4189890495bfdf762279",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":97},
            "size":{
              "width":166,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b8ecfc31a4c4d8ab772d384e5a8b1e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":97},
                "size":{
                  "width":166,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确定页/u13.png"}},
{
          "id":"6dcb322b08ef4da182178eebfa55f4ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":117},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a504f15f13334a28bb9545b5b45316dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":117},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5fd1a246b664c13b1d9faf495a073ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":117},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c639a56643a42f58412ead64738bef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":117},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f92a5dccf26048e5a94c5936a05e3b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":117},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9ee071e9a34d8db5e87d4ed63f7f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":651,
                  "y":117},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f65202f4145424d97d3c537e2c2b42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":47,
              "y":173},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4bce5f5f2ff48cb9c9eb621ec0230c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":47,
                  "y":173},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f563e9affb14e088aff932ba1e92891",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":171},
            "size":{
              "width":313,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"1a1ce704d8394e1da50cb9982d66c977",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":219},
            "size":{
              "width":457,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca311aac9984f88ac4e2c48c9026936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":219},
                "size":{
                  "width":457,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确定页/u24.png"}},
{
          "id":"dc55a3e24ed641eaa9a51fa71f01dd17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":230},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86d9fed29159463d96db6c2d7db5857b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":230},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"335b0562661149adb366637ccf61d2c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":230},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b95d29c045484bdab1ea52382e51812e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":230},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f85bd3223742e39419b0b39b48b96c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":257},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad6a76a10973421e8821802e3bab453a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":257},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21a440e977e047ff8e26e7ff9dfb7bca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":861,
              "y":282},
            "size":{
              "width":139,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af614739bb04cb2b299959fb4182586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":861,
                  "y":282},
                "size":{
                  "width":139,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确定页/u32.png"}},
{
          "id":"b60b302110894f44a2877b4f9c8a5dab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":21,
              "y":363},
            "size":{
              "width":980,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b1da0286114b989b0432669891bd48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":21,
                  "y":363},
                "size":{
                  "width":980,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确定页/u34.png"}},
{
          "id":"441a047e26864e68833ea74404a416d6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":338},
            "size":{
              "width":980,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单确定页/u36_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa3b8d00517248ebb55d3e4b373b41cc":{
      "scriptId":"u0"},
    "752678b54ff64da98ec86d22b68d7334":{
      "scriptId":"u1"},
    "b49ae2ca607b42f98c38dc649ccfd2d4":{
      "scriptId":"u2"},
    "ba1a014f99a940e9830a98ffc335aad4":{
      "scriptId":"u3"},
    "a587617e31b5462b808d13f0694af34d":{
      "scriptId":"u4"},
    "877ec16fe76b47d69374ad832777ea2b":{
      "scriptId":"u5"},
    "ab734cfebfa645f2891978d3ba438878":{
      "scriptId":"u6"},
    "7c2182ca2e1d4d45834550e547de9547":{
      "scriptId":"u7"},
    "8bb63809f863455a9cb375389ff750a1":{
      "scriptId":"u8"},
    "68c10d45c5d34982b309c8a52c87ce35":{
      "scriptId":"u9"},
    "2dd16ab31c534bbba7d10b46557b0a16":{
      "scriptId":"u10"},
    "c628371939974c9f989b0e6806fe1281":{
      "scriptId":"u11"},
    "5ac641e667b947cba37957c48fc2f8c3":{
      "scriptId":"u12"},
    "56c68c2e4c1e4189890495bfdf762279":{
      "scriptId":"u13"},
    "0b8ecfc31a4c4d8ab772d384e5a8b1e5":{
      "scriptId":"u14"},
    "6dcb322b08ef4da182178eebfa55f4ae":{
      "scriptId":"u15"},
    "a504f15f13334a28bb9545b5b45316dd":{
      "scriptId":"u16"},
    "d5fd1a246b664c13b1d9faf495a073ac":{
      "scriptId":"u17"},
    "6c639a56643a42f58412ead64738bef3":{
      "scriptId":"u18"},
    "f92a5dccf26048e5a94c5936a05e3b90":{
      "scriptId":"u19"},
    "de9ee071e9a34d8db5e87d4ed63f7f3d":{
      "scriptId":"u20"},
    "1f65202f4145424d97d3c537e2c2b42b":{
      "scriptId":"u21"},
    "f4bce5f5f2ff48cb9c9eb621ec0230c8":{
      "scriptId":"u22"},
    "9f563e9affb14e088aff932ba1e92891":{
      "scriptId":"u23"},
    "1a1ce704d8394e1da50cb9982d66c977":{
      "scriptId":"u24"},
    "0ca311aac9984f88ac4e2c48c9026936":{
      "scriptId":"u25"},
    "dc55a3e24ed641eaa9a51fa71f01dd17":{
      "scriptId":"u26"},
    "86d9fed29159463d96db6c2d7db5857b":{
      "scriptId":"u27"},
    "335b0562661149adb366637ccf61d2c5":{
      "scriptId":"u28"},
    "b95d29c045484bdab1ea52382e51812e":{
      "scriptId":"u29"},
    "50f85bd3223742e39419b0b39b48b96c":{
      "scriptId":"u30"},
    "ad6a76a10973421e8821802e3bab453a":{
      "scriptId":"u31"},
    "21a440e977e047ff8e26e7ff9dfb7bca":{
      "scriptId":"u32"},
    "1af614739bb04cb2b299959fb4182586":{
      "scriptId":"u33"},
    "b60b302110894f44a2877b4f9c8a5dab":{
      "scriptId":"u34"},
    "29b1da0286114b989b0432669891bd48":{
      "scriptId":"u35"},
    "441a047e26864e68833ea74404a416d6":{
      "scriptId":"u36"}}});