/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-13 09:26:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.modules.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class singleProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.5.RELEASE.jar", Long.valueOf(1455076070612L));
    _jspx_dependants.put("jar:file:/E:/121.42.185.68/www.shop.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/jiuji/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/121.42.185.68/www.shop.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/jiuji/WEB-INF/lib/spring-webmvc-4.0.5.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1400538092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1457321862999L));
    _jspx_dependants.put("jar:file:/E:/121.42.185.68/www.shop.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/jiuji/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/121.42.185.68/www.shop.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/jiuji/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/view/commons/taglib.jsp", Long.valueOf(1462771854843L));
    _jspx_dependants.put("jar:file:/E:/121.42.185.68/www.shop.com/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/jiuji/WEB-INF/lib/spring-webmvc-4.0.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1400538092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write(" <link rel=\"shortcut icon\" href=\"image/ico.png\" />\r\n");
      out.write("  <meta name=\"description\" content=\"啾唧网 方便快捷，物美价廉，更快送达，诚信服务\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"啾唧商品页\" />\r\n");
      out.write("<title>啾唧-商品页</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/base.css\" type=\"text/css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/top.css\" type=\"text/css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/goods.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/homepage/base.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/head.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery_1.8.3.min.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/responsive.tabs.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/head.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var ctx ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("$(document).ready(function(){ \r\n");
      out.write("\t$('.tabs').respTabs({\r\n");
      out.write("\t\tresponsive : false\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("     $(function(){\r\n");
      out.write("         //通用头部搜索切换\r\n");
      out.write("         $('#search-hd .search-input').on('input propertychange',function(){\r\n");
      out.write("             var val = $(this).val();\r\n");
      out.write("             if(val.length > 0){\r\n");
      out.write("                 $('#search-hd .pholder').hide(0);\r\n");
      out.write("             }else{\r\n");
      out.write("                 var index = $('#search-bd li.selected').index();\r\n");
      out.write("                 $('#search-hd .pholder').eq(index).show().siblings('.pholder').hide(0);\r\n");
      out.write("             }\r\n");
      out.write("         })  \r\n");
      out.write("     }) \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"top\">\r\n");
      out.write("\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<div class=\"wel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>欢迎来到啾唧网</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userCtrl/login.do\" target=\"_self\">请登录</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/homePageCtrl/toRegister.do\" target=\"_self\">免费注册</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"personal\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">个人中心</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">收藏夹</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">购物车</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">网站导航</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\r\n");
      out.write("  <div class=\"search\">\r\n");
      out.write("\t\t<div class=\"search-con\">\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("               <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/homePageCtrl/toHomePage.do\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/homepage/logo2.png\" width=\"145\" alt=\"\" /></a>\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t<div id=\"search-bd\" class=\"search-bd\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"selected\">找商品</li>\r\n");
      out.write("\t\t\t\t\t\t<li>找商家</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"search-hd\" class=\"search-hd\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search-bg\"></div>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"autocomplete-ajax\" class=\"search-input\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"s2\" class=\"search-input\"> \r\n");
      out.write("\t\t\t\t\t<span class=\"s1 pholder\">生鲜水果半价抢疯</span> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"s2 pholder\" style=\"display:none\">搜商家名称</span>\r\n");
      out.write("\t\t\t\t\t<button id=\"submit\" class=\"btn-search\" value=\"搜索\">搜索</button>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t <div id=\"selction-ajax\"></div> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("     <div class=\"content\">\r\n");
      out.write("        \t<div class=\"headNav\"> \r\n");
      out.write("\t\t\t<div class=\"navCon w1020\"> \r\n");
      out.write("\t\t\t\t<div class=\"navCon-cate fl navCon_on\"> \r\n");
      out.write("\t\t\t\t\t<div class=\"navCon-cate-title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">全部商品分类</a>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<div class=\"cateMenu hide\"> \r\n");
      out.write("\t\t\t\t\t\t<ul> \r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("\t\t\t\t\t\t</ul> \r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navCon-menu fl\"> \r\n");
      out.write("\t\t\t\t\t<ul> \r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"curMenu\" href=\"#\">首页</a></li>\r\n");
      out.write("                        <li><a href=\"#\">团购场</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">自营超市</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">名家鉴赏</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">闪购</a></li> \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">VIP专场</a></li> \r\n");
      out.write("\t\t\t\t\t</ul>  \r\n");
      out.write("\t\t\t</div>  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"goods\">\r\n");
      out.write("\t\t<div class=\"preview-left\">\r\n");
      out.write("\t\t\t<div id=\"vertical\" class=\"bigImg\">\r\n");
      out.write("\t\t\t       ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t\t<div style=\"display: none;\" id=\"winSelector\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--bigImg end-->\r\n");
      out.write("\t\t\t<div class=\"smallImg\">\r\n");
      out.write("\t\t\t\t<div class=\"scrollbutton smallImgUp disabled\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"imageMenu\">\r\n");
      out.write("\t\t\t\t\t<ul> \r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"scrollbutton smallImgDown\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--smallImg end-->\r\n");
      out.write("\t\t\t<div id=\"bigView\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<img width=\"800\" height=\"800\" alt=\"\" src=\"\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"preview-right\">\r\n");
      out.write("\t\t\t<h1 class=\"goods-title\">\r\n");
      out.write("\t\t\t\t<span itemprop=\"name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${singleProduct.FProductName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\" goods-main\">\r\n");
      out.write("\t\t\t\t<div class=\"main-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"property-box\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"property-type\">价格：</span> <span class=\"origin-price\">¥22</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"property-box\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"property-type\" style=\"font-size:16px;\"> 本站价 ：</span> <span class=\"now-price\">¥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${singleProduct.FPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"property-extra\">\r\n");
      out.write("\t\t\t\t\t<span class=\"mr\">评价： <span class=\"num\"> 9 </span>\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"mr\">累计销量： <span class=\"num SaleNum\"> 84\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t&nbsp; \r\n");
      out.write("            <div style=\"margin:5px 0;padding:5px;display:block;font-size:16px;\">运费:<span>&nbsp免费</span></div>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<div class=\"\" style=\"margin:5px 0;padding:5px;border-top:solid red 1px;border-bottom:solid red 1px;font-size:16px;\">数量:<span>&nbsp100</span></div>\r\n");
      out.write("\t\t\t&nbsp; &nbsp; \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t<!-- <div class=\"\">地址</div> -->\r\n");
      out.write("\t\t\t<div class=\"buy\">\r\n");
      out.write("\t\t\t\t<div class=\"buy-btn\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">立即购买</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"shop\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">加入购物车</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("       <div style=\"clear:both\"></div>\r\n");
      out.write("\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t<ul class=\"tabs-list\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"javascript:;\">产品详情</a></li>\r\n");
      out.write("\t\t\t    <li><a href=\"javascript:;\">累计评价</a></li> \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"tabs-container\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<!-- <h4>品牌名称：大红枣</h4> -->\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${singleProduct.FProductDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t <p><span>暂无评论</span></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ------------------------------------------------------- -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-content\">\r\n");
      out.write("\t\t\t<div class=\"cooperation\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">商家入驻</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">销售联盟</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">商品专题</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">热门搜索</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">服务热线</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"copy\">&copy;2000-2016&nbsp;&nbsp;啾唧在线电子商务有限公司&nbsp;&nbsp;&nbsp;版权所有 皖ICP备16007801号</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/header.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--preview end-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t// 图片上下滚动\r\n");
      out.write("\tvar count = $(\"#imageMenu li\").length - 4; /* 显示 5 个 li标签内容 */\r\n");
      out.write("\tvar interval = $(\"#imageMenu li:first\").width();\r\n");
      out.write("\tvar curIndex = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t$('.scrollbutton').click(function(){\r\n");
      out.write("\t\tif( $(this).hasClass('disabled') ) return false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ($(this).hasClass('smallImgUp')) --curIndex;\r\n");
      out.write("\t\telse ++curIndex;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.scrollbutton').removeClass('disabled');\r\n");
      out.write("\t\tif (curIndex == 0) $('.smallImgUp').addClass('disabled');\r\n");
      out.write("\t\tif (curIndex == count-1) $('.smallImgDown').addClass('disabled');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#imageMenu ul\").stop(false, true).animate({\"marginLeft\" : -curIndex*interval + \"px\"}, 600);\r\n");
      out.write("\t});\t\r\n");
      out.write("\t// 解决 ie6 select框 问题\r\n");
      out.write("\t$.fn.decorateIframe = function(options) {\r\n");
      out.write("        if ($.browser.msie && $.browser.version < 7) {\r\n");
      out.write("            var opts = $.extend({}, $.fn.decorateIframe.defaults, options);\r\n");
      out.write("            $(this).each(function() {\r\n");
      out.write("                var $myThis = $(this);\r\n");
      out.write("                //创建一个IFRAME\r\n");
      out.write("                var divIframe = $(\"<iframe />\");\r\n");
      out.write("                divIframe.attr(\"id\", opts.iframeId);\r\n");
      out.write("                divIframe.css(\"position\", \"absolute\");\r\n");
      out.write("                divIframe.css(\"display\", \"none\");\r\n");
      out.write("                divIframe.css(\"display\", \"block\");\r\n");
      out.write("                divIframe.css(\"z-index\", opts.iframeZIndex);\r\n");
      out.write("                divIframe.css(\"border\");\r\n");
      out.write("                divIframe.css(\"top\", \"0\");\r\n");
      out.write("                divIframe.css(\"left\", \"0\");\r\n");
      out.write("                if (opts.width == 0) {\r\n");
      out.write("                    divIframe.css(\"width\", $myThis.width() + parseInt($myThis.css(\"padding\")) * 2 + \"px\");\r\n");
      out.write("                }\r\n");
      out.write("                if (opts.height == 0) {\r\n");
      out.write("                    divIframe.css(\"height\", $myThis.height() + parseInt($myThis.css(\"padding\")) * 2 + \"px\");\r\n");
      out.write("                }\r\n");
      out.write("                divIframe.css(\"filter\", \"mask(color=#fff)\");\r\n");
      out.write("                $myThis.append(divIframe);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    $.fn.decorateIframe.defaults = {\r\n");
      out.write("        iframeId: \"decorateIframe1\",\r\n");
      out.write("        iframeZIndex: -1,\r\n");
      out.write("        width: 0,\r\n");
      out.write("        height: 0\r\n");
      out.write("    }\r\n");
      out.write("    //放大镜视窗\r\n");
      out.write("    $(\"#bigView\").decorateIframe();\r\n");
      out.write("    //点击到中图\r\n");
      out.write("    var midChangeHandler = null;\r\n");
      out.write("\t\r\n");
      out.write("    $(\"#imageMenu li img\").bind(\"click\", function(){\r\n");
      out.write("\t\tif ($(this).attr(\"id\") != \"onlickImg\") {\r\n");
      out.write("\t\t\tmidChange($(this).attr(\"src\").replace(\"small\", \"mid\"));\r\n");
      out.write("\t\t\t$(\"#imageMenu li\").removeAttr(\"id\");\r\n");
      out.write("\t\t\t$(this).parent().attr(\"id\", \"onlickImg\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}).bind(\"mouseover\", function(){\r\n");
      out.write("\t\tif ($(this).attr(\"id\") != \"onlickImg\") {\r\n");
      out.write("\t\t\twindow.clearTimeout(midChangeHandler);\r\n");
      out.write("\t\t\tmidChange($(this).attr(\"src\").replace(\"small\", \"mid\"));\r\n");
      out.write("\t\t\t$(this).css({ \"border\": \"3px solid #959595\" });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}).bind(\"mouseout\", function(){\r\n");
      out.write("\t\tif($(this).attr(\"id\") != \"onlickImg\"){\r\n");
      out.write("\t\t\t$(this).removeAttr(\"style\");\r\n");
      out.write("\t\t\tmidChangeHandler = window.setTimeout(function(){\r\n");
      out.write("\t\t\t\tmidChange($(\"#onlickImg img\").attr(\"src\").replace(\"small\", \"mid\"));\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("    function midChange(src) {\r\n");
      out.write("        $(\".midimg\").attr(\"src\", src).load(function() {\r\n");
      out.write("            changeViewImg();\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    //大视窗看图\r\n");
      out.write("    function mouseover(e) {\r\n");
      out.write("        if ($(\"#winSelector\").css(\"display\") == \"none\") {\r\n");
      out.write("            $(\"#winSelector,#bigView\").show();\r\n");
      out.write("        }\r\n");
      out.write("        $(\"#winSelector\").css(fixedPosition(e));\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("    }\r\n");
      out.write("    function mouseOut(e) {\r\n");
      out.write("        if ($(\"#winSelector\").css(\"display\") != \"none\") {\r\n");
      out.write("            $(\"#winSelector,#bigView\").hide();\r\n");
      out.write("        }\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#midimg\").mouseover(mouseover); //中图事件\r\n");
      out.write("    $(\"#midimg,#winSelector\").mousemove(mouseover).mouseout(mouseOut); //选择器事件\r\n");
      out.write("\r\n");
      out.write("    var $divWidth = $(\"#winSelector\").width(); //选择器宽度\r\n");
      out.write("    var $divHeight = $(\"#winSelector\").height(); //选择器高度\r\n");
      out.write("    var $imgWidth = $(\"#midimg\").width(); //中图宽度\r\n");
      out.write("    var $imgHeight = $(\"#midimg\").height(); //中图高度\r\n");
      out.write("    var $viewImgWidth = $viewImgHeight = $height = null; //IE加载后才能得到 大图宽度 大图高度 大图视窗高度\r\n");
      out.write("\r\n");
      out.write("    function changeViewImg() {\r\n");
      out.write("        $(\"#bigView img\").attr(\"src\", $(\"#midimg\").attr(\"src\").replace(\"mid\", \"big\"));\r\n");
      out.write("    }\r\n");
      out.write("    changeViewImg();\r\n");
      out.write("    $(\"#bigView\").scrollLeft(0).scrollTop(0);\r\n");
      out.write("    function fixedPosition(e) {\r\n");
      out.write("        if (e == null) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        var $imgLeft = $(\"#midimg\").offset().left; //中图左边距\r\n");
      out.write("        var $imgTop = $(\"#midimg\").offset().top; //中图上边距\r\n");
      out.write("        X = e.pageX - $imgLeft - $divWidth / 2; //selector顶点坐标 X\r\n");
      out.write("        Y = e.pageY - $imgTop - $divHeight / 2; //selector顶点坐标 Y\r\n");
      out.write("        X = X < 0 ? 0 : X;\r\n");
      out.write("        Y = Y < 0 ? 0 : Y;\r\n");
      out.write("        X = X + $divWidth > $imgWidth ? $imgWidth - $divWidth : X;\r\n");
      out.write("        Y = Y + $divHeight > $imgHeight ? $imgHeight - $divHeight : Y;\r\n");
      out.write("\r\n");
      out.write("        if ($viewImgWidth == null) {\r\n");
      out.write("            $viewImgWidth = $(\"#bigView img\").outerWidth();\r\n");
      out.write("            $viewImgHeight = $(\"#bigView img\").height();\r\n");
      out.write("            if ($viewImgWidth < 200 || $viewImgHeight < 200) {\r\n");
      out.write("                $viewImgWidth = $viewImgHeight = 800;\r\n");
      out.write("            }\r\n");
      out.write("            $height = $divHeight * $viewImgHeight / $imgHeight;\r\n");
      out.write("            $(\"#bigView\").width($divWidth * $viewImgWidth / $imgWidth);\r\n");
      out.write("            $(\"#bigView\").height($height);\r\n");
      out.write("        }\r\n");
      out.write("        var scrollX = X * $viewImgWidth / $imgWidth;\r\n");
      out.write("        var scrollY = Y * $viewImgHeight / $imgHeight;\r\n");
      out.write("        $(\"#bigView img\").css({ \"left\": scrollX * -1, \"top\": scrollY * -1 });\r\n");
      out.write("        $(\"#bigView\").css({ \"top\": 220, \"left\": $(\".preview-left\").offset().left + $(\".preview-left\").width() + 15 });\r\n");
      out.write("\r\n");
      out.write("        return { left: X, top: Y };\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/commons/taglib.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/view/commons/taglib.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/commons/taglib.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/view/commons/taglib.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("ctxStatic");
    // /WEB-INF/view/commons/taglib.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/commons/taglib.jsp(7,0) '${pageContext.request.contextPath}/static'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}/static",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/view/modules/product/singleProduct.jsp(99,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("tClass");
    // /WEB-INF/view/modules/product/singleProduct.jsp(99,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/modules/product/singleProduct.jsp(99,6) '${tclasses}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tclasses}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t        <li style=\"border-top: none;\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"cate-tag\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<strong><a href=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tClass.FClsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</a></strong>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"list-item hide\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t<ul class=\"itemleft\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<dl> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <dt>水果/蔬菜</dt> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<dd>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t        ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</dd> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</dl>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t</ul>  \r\n");
          out.write("\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/view/modules/product/singleProduct.jsp(109,19) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("sonTClass");
    // /WEB-INF/view/modules/product/singleProduct.jsp(109,19) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/modules/product/singleProduct.jsp(109,19) '${tClass.sonTClasses}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tClass.sonTClasses}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    <a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sonTClass.FClsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/view/modules/product/singleProduct.jsp(138,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("t_picture");
    // /WEB-INF/view/modules/product/singleProduct.jsp(138,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/modules/product/singleProduct.jsp(138,10) '${t_pictures}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${t_pictures}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/images/product/mid/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t_picture.fMidPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"400\" height=\"400\" alt=\"\" id=\"midimg\" />\r\n");
          out.write("                   ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/view/modules/product/singleProduct.jsp(148,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("t_picture");
    // /WEB-INF/view/modules/product/singleProduct.jsp(148,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/modules/product/singleProduct.jsp(148,5) '${t_pictures}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${t_pictures}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<li  id=\"onlickImg\"><img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxStatic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/images/product/small/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t_picture.fSmall}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"68\"\r\n");
          out.write("\t\t\t\t\t\t\theight=\"68\" alt=\"水果\" /></li>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
