package com.jiuji.cn.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCatalog generated by hbm2java
 */
@Entity
@Table(name = "t_catalog", catalog = "shop")
public class TCatalog implements java.io.Serializable {

	private int id;
	private String name;
	private Integer pid;
	private Integer state;

	public TCatalog() {
	}

	public TCatalog(int id) {
		this.id = id;
	}

	public TCatalog(int id, String name, Integer pid, Integer state) {
		this.id = id;
		this.name = name;
		this.pid = pid;
		this.state = state;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 44)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
