package com.jiuji.cn.model; 
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEvaluate generated by hbm2java
 */
@Entity
@Table(name = "t_evaluate", catalog = "shop")
public class TEvaluate implements java.io.Serializable {

	private String FEvaluateId;
	private String FOrderId;
	private String FUserId;
	private String FContent;
	private Date FTime;

	public TEvaluate() {
	}

	public TEvaluate(String FEvaluateId) {
		this.FEvaluateId = FEvaluateId;
	}

	public TEvaluate(String FEvaluateId, String FOrderId, String FUserId, String FContent, Date FTime) {
		this.FEvaluateId = FEvaluateId;
		this.FOrderId = FOrderId;
		this.FUserId = FUserId;
		this.FContent = FContent;
		this.FTime = FTime;
	}

	@Id

	@Column(name = "F_EvaluateId", unique = true, nullable = false, length = 44)
	public String getFEvaluateId() {
		return this.FEvaluateId;
	}

	public void setFEvaluateId(String FEvaluateId) {
		this.FEvaluateId = FEvaluateId;
	}

	@Column(name = "F_OrderId", length = 44)
	public String getFOrderId() {
		return this.FOrderId;
	}

	public void setFOrderId(String FOrderId) {
		this.FOrderId = FOrderId;
	}

	@Column(name = "F_UserId", length = 44)
	public String getFUserId() {
		return this.FUserId;
	}

	public void setFUserId(String FUserId) {
		this.FUserId = FUserId;
	}

	@Column(name = "F_Content", length = 65535)
	public String getFContent() {
		return this.FContent;
	}

	public void setFContent(String FContent) {
		this.FContent = FContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_Time", length = 19)
	public Date getFTime() {
		return this.FTime;
	}

	public void setFTime(Date FTime) {
		this.FTime = FTime;
	}

}
