package com.jiuji.cn.model;
 

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUser generated by hbm2java
 */ 
public class TUser implements java.io.Serializable {

	private String FUserId;
	private String FUserName;
	private Date FBirthday;
	private String FNickName;
	private Integer FSex;
	private String FHometown;
	private String FEmail;
	private String FMobile;
	private String FPassword;
	private int FDeleted;
	private String FRealName;
	private String FIp;
	private Date FJoin;
	private Date FLast;
	private Integer FVisits;

	public TUser() {
	}

	public TUser(String FUserId, String FUserName, int FDeleted) {
		this.FUserId = FUserId;
		this.FUserName = FUserName;
		this.FDeleted = FDeleted;
	}

	public TUser(String FUserId, String FUserName, Date FBirthday, String FNickName, Integer FSex, String FHometown,
			String FEmail, String FMobile, String FPassword, int FDeleted, String FRealName, String FIp, Date FJoin,
			Date FLast, Integer FVisits) {
		this.FUserId = FUserId;
		this.FUserName = FUserName;
		this.FBirthday = FBirthday;
		this.FNickName = FNickName;
		this.FSex = FSex;
		this.FHometown = FHometown;
		this.FEmail = FEmail;
		this.FMobile = FMobile;
		this.FPassword = FPassword;
		this.FDeleted = FDeleted;
		this.FRealName = FRealName;
		this.FIp = FIp;
		this.FJoin = FJoin;
		this.FLast = FLast;
		this.FVisits = FVisits;
	}

	public TUser(String mobile, String password) {
		// TODO Auto-generated constructor stub
		this.FMobile = mobile;
		this.FPassword = password;
	}
 
	public String getFUserId() {
		return this.FUserId;
	}

	public void setFUserId(String FUserId) {
		this.FUserId = FUserId;
	}
 
	public String getFUserName() {
		return this.FUserName;
	}

	public void setFUserName(String FUserName) {
		this.FUserName = FUserName;
	}
 
	public Date getFBirthday() {
		return this.FBirthday;
	}

	public void setFBirthday(Date FBirthday) {
		this.FBirthday = FBirthday;
	}
 
	public String getFNickName() {
		return this.FNickName;
	}

	public void setFNickName(String FNickName) {
		this.FNickName = FNickName;
	}
 
	public Integer getFSex() {
		return this.FSex;
	}

	public void setFSex(Integer FSex) {
		this.FSex = FSex;
	}
 
	public String getFHometown() {
		return this.FHometown;
	}

	public void setFHometown(String FHometown) {
		this.FHometown = FHometown;
	}
 
	public String getFEmail() {
		return this.FEmail;
	}

	public void setFEmail(String FEmail) {
		this.FEmail = FEmail;
	}
 
	public String getFMobile() {
		return this.FMobile;
	}

	public void setFMobile(String FMobile) {
		this.FMobile = FMobile;
	}
 
	public String getFPassword() {
		return this.FPassword;
	}

	public void setFPassword(String FPassword) {
		this.FPassword = FPassword;
	}
 
	public int getFDeleted() {
		return this.FDeleted;
	}

	public void setFDeleted(int FDeleted) {
		this.FDeleted = FDeleted;
	}

	public String getFRealName() {
		return this.FRealName;
	}

	public void setFRealName(String FRealName) {
		this.FRealName = FRealName;
	}
 
	public String getFIp() {
		return this.FIp;
	}

	public void setFIp(String FIp) {
		this.FIp = FIp;
	}
  
	public Date getFJoin() {
		return this.FJoin;
	}

	public void setFJoin(Date FJoin) {
		this.FJoin = FJoin;
	}
 
	public Date getFLast() {
		return this.FLast;
	}

	public void setFLast(Date FLast) {
		this.FLast = FLast;
	}
 
	public Integer getFVisits() {
		return this.FVisits;
	}

	public void setFVisits(Integer FVisits) {
		this.FVisits = FVisits;
	}

	@Override
	public String toString() {
		return "TUser [FUserId=" + FUserId + ", FUserName=" + FUserName + ", FBirthday=" + FBirthday + ", FNickName="
				+ FNickName + ", FSex=" + FSex + ", FHometown=" + FHometown + ", FEmail=" + FEmail + ", FMobile="
				+ FMobile + ", FPassword=" + FPassword + ", FDeleted=" + FDeleted + ", FRealName=" + FRealName
				+ ", FIp=" + FIp + ", FJoin=" + FJoin + ", FLast=" + FLast + ", FVisits=" + FVisits + "]";
	}

}
